-- ZeroCraft: NPC Books. Every NPC you can summon, bundled 14 to a book plus a Flight Master in every book.
-- Use the book, pick an NPC, and it appears right in front of you, facing you. Books are never used up.
USE acore_world;
CREATE TABLE IF NOT EXISTS zerocraft_nbook (item_entry INT UNSIGNED NOT NULL PRIMARY KEY, quality TINYINT UNSIGNED NOT NULL, name VARCHAR(80) NOT NULL, description VARCHAR(255) NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS zerocraft_nbook_npcs (item_entry INT UNSIGNED NOT NULL, idx INT UNSIGNED NOT NULL, kind INT UNSIGNED NOT NULL, entry INT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (item_entry, idx)) ENGINE=InnoDB;
DELETE FROM zerocraft_nbook; DELETE FROM zerocraft_nbook_npcs;

DROP TEMPORARY TABLE IF EXISTS zc_ids;
CREATE TEMPORARY TABLE zc_ids (n INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, item INT UNSIGNED NOT NULL);
INSERT INTO zc_ids (item) VALUES (16176),(16177),(16178),(16179),(16180),(16181),(16182),(16183),(16184),(16185),(16186),(16187),(16188),(17889),(17890),(17910),(17911),(18063),(19322),(19932),(20364),(21274),(21628),(21629),(21630),(21631),(21632),(21633),(21634),(21636),(21637),(21638),(21641),(21642),(21643),(21644),(21646),(21649),(21653),(21655),(21656),(21657),(21658),(21659),(21660),(21661),(21662),(21811),(21923),(21930),(21962),(21963),(21964),(22026),(22027),(22045),(23228),(23245),(23325),(23696),(23698),(23699),(28209),(29225),(31716),(33183),(34484),(34486),(38265),(39163),(41605),(41606),(42590),(44114),(45026),(45028),(45029),(45030),(45031),(45032),(45033),(45034),(45035),(45036),(45199),(45229),(45230),(45231),(45568),(45569);

DROP TEMPORARY TABLE IF EXISTS zc_cand;
CREATE TEMPORARY TABLE zc_cand (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, catord INT, cat VARCHAR(40), kind INT UNSIGNED, entry INT UNSIGNED, name VARCHAR(100));
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 1, 'Heroes', 951, MIN(h.entry), ct.name FROM zerocraft_hero_pool h JOIN creature_template ct ON ct.entry = h.entry WHERE h.villain = 0 GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 2, 'Villains', 951, MIN(h.entry), ct.name FROM zerocraft_hero_pool h JOIN creature_template ct ON ct.entry = h.entry WHERE h.villain <> 0 GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 3, 'City Guards', 823, MIN(g.entry), ct.name FROM zerocraft_guard_pool g JOIN creature_template ct ON ct.entry = g.entry WHERE g.kind = 'guard' GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 4, 'Soldiers', 823, MIN(g.entry), ct.name FROM zerocraft_guard_pool g JOIN creature_template ct ON ct.entry = g.entry WHERE g.kind = 'faction' GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 5, 'Dungeon Elites', 823, MIN(g.entry), ct.name FROM zerocraft_guard_pool g JOIN creature_template ct ON ct.entry = g.entry WHERE g.kind = 'dungeon' GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 6, 'Entertainers', p.item_entry, MIN(p.npc_entry), ct.name FROM zerocraft_deploy_pool p JOIN creature_template ct ON ct.entry = p.npc_entry WHERE p.item_entry IN (1267, 6213, 17163) GROUP BY p.item_entry, ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 7, 'Bankers', 3513, MIN(ct.entry), ct.name FROM zerocraft_removed_creatures r JOIN creature_template ct ON ct.entry = r.id
WHERE (ct.npcflag & 0x20000) <> 0 AND ct.`rank` <> 3 AND ct.entry NOT IN (4949,10181,2425,3057,2784,7999,4968,29611,16802,17468,10182,1748,25237,7937,3516,10540)  GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 8, 'Auctioneers', 1078, MIN(ct.entry), ct.name FROM zerocraft_removed_creatures r JOIN creature_template ct ON ct.entry = r.id
WHERE (ct.npcflag & 0x200000) <> 0 AND ct.`rank` <> 3 AND ct.entry NOT IN (4949,10181,2425,3057,2784,7999,4968,29611,16802,17468,10182,1748,25237,7937,3516,10540)  GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 9, 'Innkeepers', 25747, MIN(ct.entry), ct.name FROM zerocraft_removed_creatures r JOIN creature_template ct ON ct.entry = r.id
WHERE (ct.npcflag & 0x10000) <> 0 AND ct.`rank` <> 3 AND ct.entry NOT IN (4949,10181,2425,3057,2784,7999,4968,29611,16802,17468,10182,1748,25237,7937,3516,10540)  GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 10, 'Stable Masters', 17163, MIN(ct.entry), ct.name FROM zerocraft_removed_creatures r JOIN creature_template ct ON ct.entry = r.id
WHERE (ct.npcflag & 0x400000) <> 0 AND ct.`rank` <> 3 AND ct.entry NOT IN (4949,10181,2425,3057,2784,7999,4968,29611,16802,17468,10182,1748,25237,7937,3516,10540)  GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 11, 'Smiths and Repairers', 25748, MIN(ct.entry), ct.name FROM zerocraft_removed_creatures r JOIN creature_template ct ON ct.entry = r.id
WHERE (ct.npcflag & 0x1000) <> 0 AND ct.`rank` <> 3 AND ct.entry NOT IN (4949,10181,2425,3057,2784,7999,4968,29611,16802,17468,10182,1748,25237,7937,3516,10540)  GROUP BY ct.name;
INSERT INTO zc_cand (catord, cat, kind, entry, name)
SELECT 12, 'Merchants', 842, MIN(ct.entry), ct.name FROM zerocraft_removed_creatures r JOIN creature_template ct ON ct.entry = r.id
WHERE (ct.npcflag & 128) <> 0 AND ct.`rank` <> 3 AND ct.entry NOT IN (4949,10181,2425,3057,2784,7999,4968,29611,16802,17468,10182,1748,25237,7937,3516,10540) AND (ct.npcflag & (0x1000|0x10000|0x20000|0x200000|0x400000|0x2000)) = 0 GROUP BY ct.name;

DROP TEMPORARY TABLE IF EXISTS zc_cand2;
CREATE TEMPORARY TABLE zc_cand2
SELECT catord, cat, kind, entry, name, (ROW_NUMBER() OVER (PARTITION BY catord ORDER BY name, entry) - 1) DIV 14 AS b,
       (ROW_NUMBER() OVER (PARTITION BY catord ORDER BY name, entry) - 1) MOD 14 + 1 AS idx
FROM zc_cand;
DROP TEMPORARY TABLE IF EXISTS zc_books;
CREATE TEMPORARY TABLE zc_books
SELECT catord, cat, b, ROW_NUMBER() OVER (ORDER BY catord, b) AS n FROM (SELECT DISTINCT catord, cat, b FROM zc_cand2) x;
DROP TEMPORARY TABLE IF EXISTS zc_catcount;
CREATE TEMPORARY TABLE zc_catcount SELECT catord, COUNT(*) AS books FROM zc_books GROUP BY catord;

INSERT INTO zerocraft_nbook (item_entry, quality, name, description)
SELECT i.item,
       CASE WHEN bk.catord IN (1, 2) THEN 4 WHEN bk.catord = 12 THEN 2 ELSE 3 END,
       CONCAT('NPC Book: ', bk.cat, IF(c.books > 1, CONCAT(' ', COALESCE(ELT(bk.b + 1, 'I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI','XXII','XXIII','XXIV','XXV','XXVI','XXVII','XXVIII','XXIX','XXX','XXXI','XXXII','XXXIII','XXXIV','XXXV','XXXVI','XXXVII','XXXVIII','XXXIX','XL'), CAST(bk.b + 1 AS CHAR)))), '')),
       'Calls a Flight Master and more. They arrive right in front of you.'
FROM zc_books bk JOIN zc_ids i ON i.n = bk.n JOIN zc_catcount c ON c.catord = bk.catord;

INSERT INTO zerocraft_nbook_npcs (item_entry, idx, kind, entry, name)
SELECT i.item, c.idx, c.kind, c.entry, LEFT(c.name, 100)
FROM zc_cand2 c JOIN zc_books bk ON bk.catord = c.catord AND bk.b = c.b JOIN zc_ids i ON i.n = bk.n;
-- every book: a Flight Master first (one from your own side, picked when you call him)
INSERT INTO zerocraft_nbook_npcs (item_entry, idx, kind, entry, name)
SELECT item_entry, 0, 3504, 0, 'Flight Master' FROM zerocraft_nbook;
UPDATE zerocraft_nbook b SET description = CONCAT('Calls a Flight Master and ', (SELECT COUNT(*) - 1 FROM zerocraft_nbook_npcs n WHERE n.item_entry = b.item_entry), ' more. They arrive right in front of you.');

-- the book items (cloned from the Builder's Kit, never used up)
DELETE FROM item_template WHERE entry = 16176 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16176);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16176 SET z.entry = 16176, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16176;
DELETE FROM item_template WHERE entry = 16177 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16177);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16177 SET z.entry = 16177, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16177;
DELETE FROM item_template WHERE entry = 16178 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16178);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16178 SET z.entry = 16178, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16178;
DELETE FROM item_template WHERE entry = 16179 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16179);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16179 SET z.entry = 16179, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16179;
DELETE FROM item_template WHERE entry = 16180 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16180);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16180 SET z.entry = 16180, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16180;
DELETE FROM item_template WHERE entry = 16181 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16181);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16181 SET z.entry = 16181, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16181;
DELETE FROM item_template WHERE entry = 16182 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16182);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16182 SET z.entry = 16182, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16182;
DELETE FROM item_template WHERE entry = 16183 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16183);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16183 SET z.entry = 16183, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16183;
DELETE FROM item_template WHERE entry = 16184 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16184);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16184 SET z.entry = 16184, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16184;
DELETE FROM item_template WHERE entry = 16185 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16185);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16185 SET z.entry = 16185, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16185;
DELETE FROM item_template WHERE entry = 16186 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16186);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16186 SET z.entry = 16186, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16186;
DELETE FROM item_template WHERE entry = 16187 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16187);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16187 SET z.entry = 16187, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16187;
DELETE FROM item_template WHERE entry = 16188 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 16188);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 16188 SET z.entry = 16188, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 16188;
DELETE FROM item_template WHERE entry = 17889 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 17889);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 17889 SET z.entry = 17889, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 17889;
DELETE FROM item_template WHERE entry = 17890 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 17890);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 17890 SET z.entry = 17890, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 17890;
DELETE FROM item_template WHERE entry = 17910 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 17910);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 17910 SET z.entry = 17910, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 17910;
DELETE FROM item_template WHERE entry = 17911 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 17911);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 17911 SET z.entry = 17911, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 17911;
DELETE FROM item_template WHERE entry = 18063 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 18063);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 18063 SET z.entry = 18063, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 18063;
DELETE FROM item_template WHERE entry = 19322 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 19322);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 19322 SET z.entry = 19322, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 19322;
DELETE FROM item_template WHERE entry = 19932 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 19932);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 19932 SET z.entry = 19932, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 19932;
DELETE FROM item_template WHERE entry = 20364 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 20364);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 20364 SET z.entry = 20364, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 20364;
DELETE FROM item_template WHERE entry = 21274 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21274);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21274 SET z.entry = 21274, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21274;
DELETE FROM item_template WHERE entry = 21628 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21628);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21628 SET z.entry = 21628, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21628;
DELETE FROM item_template WHERE entry = 21629 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21629);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21629 SET z.entry = 21629, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21629;
DELETE FROM item_template WHERE entry = 21630 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21630);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21630 SET z.entry = 21630, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21630;
DELETE FROM item_template WHERE entry = 21631 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21631);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21631 SET z.entry = 21631, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21631;
DELETE FROM item_template WHERE entry = 21632 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21632);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21632 SET z.entry = 21632, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21632;
DELETE FROM item_template WHERE entry = 21633 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21633);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21633 SET z.entry = 21633, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21633;
DELETE FROM item_template WHERE entry = 21634 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21634);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21634 SET z.entry = 21634, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21634;
DELETE FROM item_template WHERE entry = 21636 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21636);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21636 SET z.entry = 21636, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21636;
DELETE FROM item_template WHERE entry = 21637 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21637);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21637 SET z.entry = 21637, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21637;
DELETE FROM item_template WHERE entry = 21638 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21638);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21638 SET z.entry = 21638, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21638;
DELETE FROM item_template WHERE entry = 21641 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21641);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21641 SET z.entry = 21641, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21641;
DELETE FROM item_template WHERE entry = 21642 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21642);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21642 SET z.entry = 21642, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21642;
DELETE FROM item_template WHERE entry = 21643 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21643);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21643 SET z.entry = 21643, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21643;
DELETE FROM item_template WHERE entry = 21644 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21644);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21644 SET z.entry = 21644, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21644;
DELETE FROM item_template WHERE entry = 21646 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21646);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21646 SET z.entry = 21646, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21646;
DELETE FROM item_template WHERE entry = 21649 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21649);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21649 SET z.entry = 21649, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21649;
DELETE FROM item_template WHERE entry = 21653 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21653);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21653 SET z.entry = 21653, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21653;
DELETE FROM item_template WHERE entry = 21655 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21655);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21655 SET z.entry = 21655, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21655;
DELETE FROM item_template WHERE entry = 21656 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21656);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21656 SET z.entry = 21656, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21656;
DELETE FROM item_template WHERE entry = 21657 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21657);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21657 SET z.entry = 21657, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21657;
DELETE FROM item_template WHERE entry = 21658 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21658);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21658 SET z.entry = 21658, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21658;
DELETE FROM item_template WHERE entry = 21659 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21659);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21659 SET z.entry = 21659, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21659;
DELETE FROM item_template WHERE entry = 21660 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21660);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21660 SET z.entry = 21660, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21660;
DELETE FROM item_template WHERE entry = 21661 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21661);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21661 SET z.entry = 21661, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21661;
DELETE FROM item_template WHERE entry = 21662 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21662);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21662 SET z.entry = 21662, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21662;
DELETE FROM item_template WHERE entry = 21811 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21811);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21811 SET z.entry = 21811, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21811;
DELETE FROM item_template WHERE entry = 21923 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21923);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21923 SET z.entry = 21923, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21923;
DELETE FROM item_template WHERE entry = 21930 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21930);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21930 SET z.entry = 21930, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21930;
DELETE FROM item_template WHERE entry = 21962 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21962);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21962 SET z.entry = 21962, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21962;
DELETE FROM item_template WHERE entry = 21963 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21963);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21963 SET z.entry = 21963, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21963;
DELETE FROM item_template WHERE entry = 21964 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 21964);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 21964 SET z.entry = 21964, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 21964;
DELETE FROM item_template WHERE entry = 22026 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 22026);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 22026 SET z.entry = 22026, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 22026;
DELETE FROM item_template WHERE entry = 22027 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 22027);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 22027 SET z.entry = 22027, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 22027;
DELETE FROM item_template WHERE entry = 22045 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 22045);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 22045 SET z.entry = 22045, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 22045;
DELETE FROM item_template WHERE entry = 23228 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 23228);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 23228 SET z.entry = 23228, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 23228;
DELETE FROM item_template WHERE entry = 23245 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 23245);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 23245 SET z.entry = 23245, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 23245;
DELETE FROM item_template WHERE entry = 23325 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 23325);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 23325 SET z.entry = 23325, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 23325;
DELETE FROM item_template WHERE entry = 23696 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 23696);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 23696 SET z.entry = 23696, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 23696;
DELETE FROM item_template WHERE entry = 23698 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 23698);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 23698 SET z.entry = 23698, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 23698;
DELETE FROM item_template WHERE entry = 23699 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 23699);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 23699 SET z.entry = 23699, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 23699;
DELETE FROM item_template WHERE entry = 28209 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 28209);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 28209 SET z.entry = 28209, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 28209;
DELETE FROM item_template WHERE entry = 29225 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 29225);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 29225 SET z.entry = 29225, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 29225;
DELETE FROM item_template WHERE entry = 31716 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 31716);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 31716 SET z.entry = 31716, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 31716;
DELETE FROM item_template WHERE entry = 33183 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 33183);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 33183 SET z.entry = 33183, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 33183;
DELETE FROM item_template WHERE entry = 34484 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 34484);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 34484 SET z.entry = 34484, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 34484;
DELETE FROM item_template WHERE entry = 34486 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 34486);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 34486 SET z.entry = 34486, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 34486;
DELETE FROM item_template WHERE entry = 38265 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 38265);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 38265 SET z.entry = 38265, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 38265;
DELETE FROM item_template WHERE entry = 39163 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 39163);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 39163 SET z.entry = 39163, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 39163;
DELETE FROM item_template WHERE entry = 41605 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 41605);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 41605 SET z.entry = 41605, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 41605;
DELETE FROM item_template WHERE entry = 41606 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 41606);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 41606 SET z.entry = 41606, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 41606;
DELETE FROM item_template WHERE entry = 42590 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 42590);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 42590 SET z.entry = 42590, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 42590;
DELETE FROM item_template WHERE entry = 44114 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 44114);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 44114 SET z.entry = 44114, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 44114;
DELETE FROM item_template WHERE entry = 45026 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45026);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45026 SET z.entry = 45026, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45026;
DELETE FROM item_template WHERE entry = 45028 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45028);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45028 SET z.entry = 45028, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45028;
DELETE FROM item_template WHERE entry = 45029 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45029);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45029 SET z.entry = 45029, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45029;
DELETE FROM item_template WHERE entry = 45030 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45030);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45030 SET z.entry = 45030, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45030;
DELETE FROM item_template WHERE entry = 45031 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45031);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45031 SET z.entry = 45031, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45031;
DELETE FROM item_template WHERE entry = 45032 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45032);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45032 SET z.entry = 45032, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45032;
DELETE FROM item_template WHERE entry = 45033 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45033);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45033 SET z.entry = 45033, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45033;
DELETE FROM item_template WHERE entry = 45034 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45034);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45034 SET z.entry = 45034, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45034;
DELETE FROM item_template WHERE entry = 45035 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45035);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45035 SET z.entry = 45035, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45035;
DELETE FROM item_template WHERE entry = 45036 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45036);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45036 SET z.entry = 45036, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45036;
DELETE FROM item_template WHERE entry = 45199 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45199);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45199 SET z.entry = 45199, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45199;
DELETE FROM item_template WHERE entry = 45229 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45229);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45229 SET z.entry = 45229, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45229;
DELETE FROM item_template WHERE entry = 45230 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45230);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45230 SET z.entry = 45230, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45230;
DELETE FROM item_template WHERE entry = 45231 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45231);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45231 SET z.entry = 45231, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45231;
DELETE FROM item_template WHERE entry = 45568 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45568);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45568 SET z.entry = 45568, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45568;
DELETE FROM item_template WHERE entry = 45569 AND EXISTS (SELECT 1 FROM zerocraft_nbook WHERE item_entry = 45569);
DROP TEMPORARY TABLE IF EXISTS zc_b;
CREATE TEMPORARY TABLE zc_b SELECT * FROM item_template WHERE entry = 8164;
UPDATE zc_b z JOIN zerocraft_nbook b ON b.item_entry = 45569 SET z.entry = 45569, z.name = b.name, z.description = b.description, z.Quality = b.quality, z.stackable = 1, z.maxcount = 0, z.bonding = 0, z.displayid = 918, z.spellid_1 = 16872, z.ScriptName = 'item_zerocraft_nbook';
INSERT INTO item_template SELECT * FROM zc_b WHERE entry = 45569;
DROP TEMPORARY TABLE IF EXISTS zc_b;

-- bosses: 25% chance of an NPC Book (green 50 / blue 35 / purple 15)
DELETE FROM reference_loot_template WHERE Entry = 911090;
INSERT INTO reference_loot_template (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment)
SELECT 911090, b.item_entry, 0, 0, 0, 1, 1, 1, 1, b.name FROM zerocraft_nbook b;
DROP TEMPORARY TABLE IF EXISTS zc_q;
CREATE TEMPORARY TABLE zc_q SELECT quality, COUNT(*) AS n FROM zerocraft_nbook GROUP BY quality;
UPDATE reference_loot_template r JOIN zerocraft_nbook b ON b.item_entry = r.Item JOIN zc_q q ON q.quality = b.quality
SET r.Chance = ROUND(CASE b.quality WHEN 2 THEN 50 WHEN 3 THEN 35 ELSE 15 END / q.n, 3) WHERE r.Entry = 911090;
DELETE FROM creature_loot_template WHERE Reference = 911090;
INSERT IGNORE INTO creature_loot_template (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment)
SELECT DISTINCT Entry, 911090, 911090, 25, 0, 1, 0, 1, 1, 'ZeroCraft NPC book' FROM creature_loot_template WHERE Reference = 911000;

SELECT name, quality FROM zerocraft_nbook ORDER BY item_entry;
SELECT COUNT(*) AS npcs_in_books FROM zerocraft_nbook_npcs WHERE idx > 0;
SELECT COUNT(*) AS book_items FROM item_template WHERE ScriptName = 'item_zerocraft_nbook';
