-- Every .tele location on the server, grouped (generated from game_tele - do not edit by hand)
-- ZC_TELE = { { group, { { label, teleName, expansionMask }, ... } }, ... }   mask: 1 vanilla, 2 TBC, 4 Wrath
ZC_TELE = {
{ "Hidden & unused", {
{"Azshara Alliance Entrance","AzsharaAllianceEntrance",1},
{"Azshara Crater","AzsharaCrater",1},
{"Azshara Horde Entrance","AzsharaHordeEntrance",1},
{"Box","Box",1},
{"Deeprun Tram","DeeprunTram",1},
{"Emerald Dream","EmeraldDream",1},
{"Emerald Dream Forest","EmeraldDreamForest",1},
{"Emerald Dream Statue","EmeraldDreamStatue",1},
{"GM Island","GMIsland",1},
{"Hall of Legends","HallOfLegends",1},
{"Hyjal Blizzard Construction Co","HyjalBlizzardConstructionCo",1},
{"Hyjal Cave Inside","HyjalCaveInside",1},
{"Hyjal Cave Outside","HyjalCaveOutside",1},
{"Hyjal Crater","HyjalCrater",1},
{"Hyjal the World Tree","HyjalTheWorldTree",1},
{"Jail Alliance","JailAlliance",1},
{"Jail Horde","JailHorde",1},
{"Jail Official","JailOfficial",1},
{"Karazhan Crypts","KarazhanCrypts",2},
{"Mine K","MineK",1},
{"Old Iron Forge","OldIronForge",1},
{"Old Scarlet Monastery","OldScarletMonastery",1},
{"Scott Test","ScottTest",1},
{"Verdant Fields","VerdantFields",1},
} },
{ "Capitals & hubs", {
{"Booty Bay","BootyBay",1},
{"Dalaran","Dalaran",4},
{"Darnassus","Darnassus",1},
{"Everlook","Everlook",1},
{"Gadgetzan","Gadgetzan",1},
{"Ironforge","Ironforge",1},
{"Menethil Harbor","MenethilHarbor",1},
{"Orgrimmar","Orgrimmar",1},
{"Ratchet","Ratchet",1},
{"Shattrath","Shattrath",2},
{"Silvermoon City","SilvermoonCity",2},
{"Stormwind","Stormwind",1},
{"The Exodar","TheExodar",2},
{"Thunder Bluff","ThunderBluff",1},
{"Undercity","Undercity",1},
} },
{ "Raids", {
{"AQ20","AQ20",1},
{"AQ40","AQ40",1},
{"Blackwing Lair Outside","BlackwingLairOutside",1},
{"Boss Anub Rekhan","BossAnubRekhan",5},
{"Boss Auriaya","BossAuriaya",4},
{"Boss Blood Queen Lanathel","BossBloodQueenLanathel",4},
{"Boss Deathbringer Saurfang","BossDeathbringerSaurfang",4},
{"Boss Festergut","BossFestergut",4},
{"Boss Flame Leviathan","BossFlameLeviathan",4},
{"Boss Freya","BossFreya",4},
{"Boss General Vezax","BossGeneralVezax",4},
{"Boss Gluth","BossGluth",5},
{"Boss Gothik the Harvester","BossGothikTheHarvester",5},
{"Boss Grand Widow Faerlina","BossGrandWidowFaerlina",5},
{"Boss Grobbulus","BossGrobbulus",5},
{"Boss Heigan the Unclean","BossHeiganTheUnclean",5},
{"Boss High Overlord Saurfang","BossHighOverlordSaurfang",4},
{"Boss Hodir","BossHodir",4},
{"Boss Ignis the Furnace Master","BossIgnisTheFurnaceMaster",4},
{"Boss Instructor Razuvious","BossInstructorRazuvious",5},
{"Boss Kel Thuzad","BossKelThuzad",5},
{"Boss Kologarn","BossKologarn",4},
{"Boss Lady Deathwhisper","BossLadyDeathwhisper",4},
{"Boss Loatheb","BossLoatheb",5},
{"Boss Lord Marrowgar","BossLordMarrowgar",4},
{"Boss Maexxna","BossMaexxna",5},
{"Boss Mimiron","BossMimiron",4},
{"Boss Muradin Bronzebeard","BossMuradinBronzebeard",4},
{"Boss Noth the Plaguebringer","BossNothThePlaguebringer",5},
{"Boss Patchwerk","BossPatchwerk",5},
{"Boss Prince Council","BossPrinceCouncil",4},
{"Boss Prince Valanar Keleseth Taldaram","BossPrinceValanarKelesethTaldaram",4},
{"Boss Professor Putricide","BossProfessorPutricide",4},
{"Boss Razorscale","BossRazorscale",4},
{"Boss Rotface","BossRotface",4},
{"Boss Sapphrion","BossSapphrion",5},
{"Boss Sindragosa","BossSindragosa",4},
{"Boss Steelbreaker","BossSteelbreaker",4},
{"Boss Thaddius","BossThaddius",5},
{"Boss the Four Horsemen","BossTheFourHorsemen",5},
{"Boss the Lich King","BossTheLichKing",4},
{"Boss Thorim","BossThorim",4},
{"Boss Valithria Dreamwalker","BossValithriaDreamwalker",4},
{"Boss XT002 Deconstructor","BossXT002Deconstructor",4},
{"Boss Yogg Saron","BossYoggSaron",4},
{"BT","BT",2},
{"BWL","BWL",1},
{"Eye","Eye",2},
{"Gruul","Gruul",2},
{"ICC Instance","ICCInstance",4},
{"Ice Crown Citadel Instance","IceCrownCitadelInstance",4},
{"Instance2159","Instance2159",5},
{"Instance3456","Instance3456",5},
{"Instance4273","Instance4273",4},
{"Instance4493","Instance4493",4},
{"Instance4500","Instance4500",4},
{"Instance4603","Instance4603",4},
{"Instance4722","Instance4722",4},
{"Instance4812","Instance4812",4},
{"Instance4987","Instance4987",4},
{"Kara","Kara",2},
{"magtheridon","magtheridon",2},
{"MC","MC",1},
{"Nax","Nax",5},
{"Naxxramas Instance","NaxxramasInstance",5},
{"Onyxia","Onyxia",5},
{"Onyxias Lair Instance","OnyxiasLairInstance",5},
{"SSC","SSC",2},
{"SWP","SWP",2},
{"The Eye of Eternity Instance","TheEyeOfEternityInstance",4},
{"The Obsidian Sanctum Instance","TheObsidianSanctumInstance",4},
{"The Ruby Sanctum Instance","TheRubySanctumInstance",4},
{"Tot C Instance","TotCInstance",4},
{"Trial of the Crusader Instance","TrialOfTheCrusaderInstance",4},
{"Ulduar Instance","UlduarInstance",4},
{"Vault of Archavon Instance","VaultOfArchavonInstance",4},
{"ZA","ZA",2},
{"ZG","ZG",1},
{"Zul Gurub Alter of Storms","ZulGurubAlterOfStorms",1},
} },
{ "Dungeons", {
{"AC","AC",2},
{"Ahnkahet Instance","AhnkahetInstance",4},
{"Arca","Arca",2},
{"Azjol Nerub Instance","AzjolNerubInstance",4},
{"Bf","Bf",2},
{"Bfd","Bfd",1},
{"Blackwing Lair","BlackwingLair",1},
{"Bota","Bota",2},
{"BRD","BRD",1},
{"Champ Instance","ChampInstance",4},
{"COS Instance","COSInstance",4},
{"Culling Instance","CullingInstance",4},
{"Deadmines","Deadmines",1},
{"Deadmines Strange Place","DeadminesStrangePlace",1},
{"Deeprun Tram Deeprun Divers","DeeprunTramDeeprunDivers",1},
{"Deeprun Tram Nessy","DeeprunTramNessy",1},
{"Deeprun Tram Underwater Location","DeeprunTramUnderwaterLocation",1},
{"DK Zone","DKZone",1},
{"Dmeast","Dmeast",1},
{"Dmnorth","Dmnorth",1},
{"Dmwest","Dmwest",1},
{"Drak Tharon Instance","DrakTharonInstance",4},
{"Echonok Caver","EchonokCaver",1},
{"Gnome","Gnome",1},
{"Gundrak Instance","GundrakInstance",4},
{"Hall of Blackhand","HallOfBlackhand",1},
{"Hall of the Crafters","HallOfTheCrafters",1},
{"Hall of the Keepers","HallOfTheKeepers",1},
{"Halls of Reflection Instance","HallsOfReflectionInstance",4},
{"Halls of Stone Instance","HallsOfStoneInstance",4},
{"Instance1196","Instance1196",4},
{"Instance206","Instance206",4},
{"Instance4100","Instance4100",4},
{"Instance4196","Instance4196",4},
{"Instance4264","Instance4264",4},
{"Instance4265","Instance4265",4},
{"Instance4277","Instance4277",4},
{"Instance4415","Instance4415",4},
{"Instance4416","Instance4416",4},
{"Instance4428","Instance4428",4},
{"Instance4494","Instance4494",4},
{"Instance4723","Instance4723",4},
{"Instance4809","Instance4809",4},
{"Instance4813","Instance4813",4},
{"Instance4820","Instance4820",4},
{"LBRS","LBRS",1},
{"Map Chamber","MapChamber",1},
{"Maraorange","Maraorange",1},
{"Marapurple","Marapurple",1},
{"Mech","Mech",2},
{"Mgt","Mgt",2},
{"Molten Core","MoltenCore",1},
{"MT","MT",2},
{"Pit of Saron Instance","PitOfSaronInstance",4},
{"Ramp","Ramp",2},
{"RFC","RFC",1},
{"RFD","RFD",1},
{"RFK","RFK",1},
{"Sethekk","Sethekk",2},
{"SFK","SFK",1},
{"SH","SH",2},
{"SL","SL",2},
{"SM Armory","SMArmory",1},
{"SM Cath","SMCath",1},
{"SMGY","SMGY",1},
{"SM Lib","SMLib",1},
{"SP","SP",2},
{"ST","ST",1},
{"Strat","Strat",1},
{"Stratholme Outside","StratholmeOutside",1},
{"SV","SV",2},
{"The Culling of Stratholme Instance","TheCullingOfStratholmeInstance",4},
{"The Forge of Souls Instance","TheForgeOfSoulsInstance",4},
{"The Nexus Instance","TheNexusInstance",4},
{"The Oculus Instance","TheOculusInstance",4},
{"The Underbog","TheUnderbog",2},
{"The Violet Hold Instance","TheVioletHoldInstance",4},
{"To C Instance","ToCInstance",4},
{"Trial of the Champion Instance","TrialOfTheChampionInstance",4},
{"UBRS","UBRS",1},
{"Ulda","Ulda",1},
{"Utgarde Keep Instance","UtgardeKeepInstance",4},
{"Utgarde Pinnacle Instance","UtgardePinnacleInstance",4},
{"WC","WC",1},
} },
{ "Battlegrounds & arenas", {
{"AB","AB",1},
{"Alterac Valley","AlteracValley",1},
{"Alterac Valley Alliance","AlteracValleyAlliance",1},
{"Alterac Valley Horde","AlteracValleyHorde",1},
{"Arathi Basin","ArathiBasin",1},
{"Arathi Basin Alliance","ArathiBasinAlliance",1},
{"Arathi Basin Horde","ArathiBasinHorde",1},
{"AV","AV",1},
{"EOTS","EOTS",2},
{"Eye of the Storm","EyeOfTheStorm",2},
{"Eye of the Storm Alliance","EyeOfTheStormAlliance",2},
{"Eye of the Storm Horde","EyeOfTheStormHorde",2},
{"Warsong Gulch","WarsongGulch",1},
{"Warsong Gulch Alliance","WarsongGulchAlliance",1},
{"Warsong Gulch Horde","WarsongGulchHorde",1},
{"WSG","WSG",1},
} },
{ "Eastern Kingdoms", {
{"Addles Stead","AddlesStead",1},
{"Aerie Peak","AeriePeak",1},
{"Agamand Mills","AgamandMills",1},
{"Agmonds End","AgmondsEnd",1},
{"Agol Watha","AgolWatha",1},
{"Alexston Farmstead","AlexstonFarmstead",1},
{"Algaz Station","AlgazStation",1},
{"Altar of Storms","AltarOfStorms",1},
{"Alterac Mountains","AlteracMountains",1},
{"Althers Mill","AlthersMill",1},
{"Ambermill","Ambermill",1},
{"Amberstill Ranch","AmberstillRanch",1},
{"Angerfang Encampment","AngerfangEncampment",1},
{"Angor Fortress","AngorFortress",1},
{"Anvilmar","Anvilmar",1},
{"Apocryphans Rest","ApocryphansRest",1},
{"Arathi Dwarven Farm","ArathiDwarvenFarm",1},
{"Arathi Highlands","ArathiHighlands",1},
{"Aridens Camp","AridensCamp",1},
{"Azurelode Mine","AzurelodeMine",1},
{"Badlands","Badlands",1},
{"Badlands Unfinished Region","BadlandsUnfinishedRegion",1},
{"Balia Mah Ruins","BaliaMahRuins",1},
{"Ballal Ruins","BallalRuins",1},
{"Balnir Farmstead","BalnirFarmstead",1},
{"Baradin Bay","BaradinBay",1},
{"Battle Ring","BattleRing",1},
{"Beggars Haunt","BeggarsHaunt",1},
{"Berens Peril","BerensPeril",1},
{"Black Channel Marsh","BlackChannelMarsh",1},
{"Blackchar Cave","BlackcharCave",1},
{"Blackchar Cave Inside","BlackcharCaveInside",1},
{"Blackrock Depths","BlackrockDepths",1},
{"Blackrock Mountain","BlackrockMountain",1},
{"Blackrock Pass","BlackrockPass",1},
{"Blackrock Spire","BlackrockSpire",1},
{"Blackrock Stronghold","BlackrockStronghold",1},
{"Blackwood Lake","BlackwoodLake",1},
{"Blasted Lands","BlastedLands",1},
{"Bloodsail Compound","BloodsailCompound",1},
{"Bluegill Marsh","BluegillMarsh",1},
{"Bogens Ledge","BogensLedge",1},
{"Boulderfist Hall","BoulderfistHall",1},
{"Boulderfist Ouspost","BoulderfistOuspost",1},
{"Boulderfist Outpost","BoulderfistOutpost",1},
{"Boulder Gor","BoulderGor",1},
{"Brackwell Pumpkin Patch","BrackwellPumpkinPatch",1},
{"Brewnall Village","BrewnallVillage",1},
{"Brightwater Lake","BrightwaterLake",1},
{"Brightwood Grove","BrightwoodGrove",1},
{"Brill","Brill",1},
{"Browman Mill","BrowmanMill",1},
{"Burning Steppes","BurningSteppes",1},
{"Caer Darrow","CaerDarrow",1},
{"Camp Boff","CampBoff",1},
{"Camp Cagg","CampCagg",1},
{"Camp Kosh","CampKosh",1},
{"Camp Wurg","CampWurg",1},
{"Canals","Canals",1},
{"Cathedral of Light","CathedralOfLight",1},
{"Cathedral Square","CathedralSquare",1},
{"Chill Breeze Valley","ChillBreezeValley",1},
{"Chillwind Camp","ChillwindCamp",1},
{"Chillwind Point","ChillwindPoint",1},
{"Circle of East Binding","CircleOfEastBinding",1},
{"Circle of Inner Binding","CircleOfInnerBinding",1},
{"Circle of Outer Binding","CircleOfOuterBinding",1},
{"Circle of West Binding","CircleOfWestBinding",1},
{"Cold Hearth Manor","ColdHearthManor",1},
{"Coldridge Pass","ColdridgePass",1},
{"Coldridge Valley","ColdridgeValley",1},
{"Corins Crossing","CorinsCrossing",1},
{"Corrahns Dagger","CorrahnsDagger",1},
{"Crown Guard Tower","CrownGuardTower",1},
{"Crusaders Outpost","CrusadersOutpost",1},
{"Crusaders Outpost Scarlet Monastery","CrusadersOutpostScarletMonastery",1},
{"Crushridge Hold","CrushridgeHold",1},
{"Crystal Lake","CrystalLake",1},
{"Crystalvein Mine","CrystalveinMine",1},
{"Dabyries Farmstead","DabyriesFarmstead",1},
{"Dalaran Crater","DalaranCrater",1},
{"Dalsons Tears ","DalsonsTears ",1},
{"Dandreds Fold","DandredsFold",1},
{"Darkshire","Darkshire",1},
{"Darrow Hill","DarrowHill",1},
{"Darrowmere Lake","DarrowmereLake",1},
{"Darrow Shire","DarrowShire",1},
{"Deadmans Crossing","DeadmansCrossing",1},
{"Deadwind Pass","DeadwindPass",1},
{"Deadwind Ravine","DeadwindRavine",1},
{"Deathknell","Deathknell",1},
{"Deathnell","Deathnell",1},
{"Deep Elem Mine","DeepElemMine",1},
{"Demonts Place","DemontsPlace",1},
{"Dig One","DigOne",1},
{"Direforge Hill","DireforgeHill",1},
{"Dracodar","Dracodar",1},
{"Dragonmaw Gates","DragonmawGates",1},
{"Dreadmaul Hold","DreadmaulHold",1},
{"Dreadmaul Post","DreadmaulPost",1},
{"Dreadmaul Rock","DreadmaulRock",1},
{"Drywhisker Gorge","DrywhiskerGorge",1},
{"Dun Algaz","DunAlgaz",1},
{"Dun Garok","DunGarok",1},
{"Dun Modr","DunModr",1},
{"Dun Morogh","DunMorogh",1},
{"Durnholde Keep","DurnholdeKeep",1},
{"Duskwood","Duskwood",1},
{"Dustfire Valley","DustfireValley",1},
{"Dwarven District","DwarvenDistrict",1},
{"Eastern Plaguelands","EasternPlaguelands",1},
{"Eastern Plaguelands Unfinished Region","EasternPlaguelandsUnfinishedRegion",1},
{"Eastern Strand","EasternStrand",1},
{"Eastvale Logging Camp","EastvaleLoggingCamp",1},
{"Eastwall Gate","EastwallGate",1},
{"Eastwall Tower","EastwallTower",1},
{"Echo Ridge Mine","EchoRidgeMine",1},
{"Elwynn Forest","ElwynnForest",1},
{"Excavation Center","ExcavationCenter",1},
{"Faldirs Cove","FaldirsCove",1},
{"Fallow Sanctuary","FallowSanctuary",1},
{"Fargodeep Mine","FargodeepMine",1},
{"Farstrider Lodge","FarstriderLodge",1},
{"Featherbeards Hovel","FeatherbeardsHovel",1},
{"Felstone Field","FelstoneField",1},
{"Fenris Isle","FenrisIsle",1},
{"Firewacht Ridge","FirewachtRidge",1},
{"Flame Crest","FlameCrest",1},
{"Forests Edge","ForestsEdge",1},
{"Frostmane Hold","FrostmaneHold",1},
{"Furlbrows Pumpkin Farm","FurlbrowsPumpkinFarm",1},
{"Gahrrons Withering","GahrronsWithering",1},
{"Gallows Corner","GallowsCorner",1},
{"Garrens Haunt","GarrensHaunt",1},
{"Garrison Armory","GarrisonArmory",1},
{"Gate of Ironforge","GateOfIronforge",1},
{"Gavins Naze","GavinsNaze",1},
{"Gillijims Isle","GillijimsIsle",1},
{"Gilneas","Gilneas",1},
{"Gnomeregan","Gnomeregan",1},
{"Gol Bolar Quarry","GolBolarQuarry",1},
{"Gold Coast Quarry","GoldCoastQuarry",1},
{"Goldshire","Goldshire",1},
{"Go Shek Farm","GoShekFarm",1},
{"Grim Batol","GrimBatol",1},
{"Grim Batol Watch Post","GrimBatolWatchPost",1},
{"Grimesilt Dig Site","GrimesiltDigSite",1},
{"Grizzlepaw Ridge","GrizzlepawRidge",1},
{"Gromgol Base Camp","GromgolBaseCamp",1},
{"Grongolbase Camp","GrongolbaseCamp",1},
{"Groshgok Compound","GroshgokCompound",1},
{"Growless Cave","GrowlessCave",1},
{"Gurubashi Arena","GurubashiArena",1},
{"Hall of Explorers","HallOfExplorers",1},
{"Hammerfall","Hammerfall",1},
{"Hammertoes Digsite","HammertoesDigsite",1},
{"Hearthglen","Hearthglen",1},
{"Helms Bed Lake","HelmsBedLake",1},
{"Heroes Vigil","HeroesVigil",1},
{"Hillsbrad Fields","HillsbradFields",1},
{"Hillsbrad Foothills","HillsbradFoothills",1},
{"Hiri Watha","HiriWatha",1},
{"Iceflow Lake","IceflowLake",1},
{"Ironbands Compound","IronbandsCompound",1},
{"Ironbands Excavation Site","IronbandsExcavationSite",1},
{"Ironbeards Tomb","IronbeardsTomb",1},
{"Ithariuss Cave","IthariussCave",1},
{"Jaguero Isle","JagueroIsle",1},
{"Janeiros Point","JaneirosPoint",1},
{"Jangolode Mine","JangolodeMine",1},
{"Jasperlode Mine","JasperlodeMine",1},
{"Jintha Alor","JinthaAlor",1},
{"Joreds Landing","JoredsLanding",1},
{"Kalai Ruins","KalaiRuins",1},
{"Karazhan","Karazhan",2},
{"Kargath","Kargath",1},
{"Kharanos","Kharanos",1},
{"Kurzens Compound","KurzensCompound",1},
{"Lake Everstill","LakeEverstill",1},
{"Lake Mereldar","LakeMereldar",1},
{"Lake Nazferiti","LakeNazferiti",1},
{"Lakeridge Highway","LakeridgeHighway",1},
{"Lakeshire","Lakeshire",1},
{"Lethlor Ravine","LethlorRavine",1},
{"Lights Hope Chapel","LightsHopeChapel",1},
{"Loch Modan","LochModan",1},
{"Longshore","Longshore",1},
{"Lordamare Lake","LordamareLake",1},
{"Lordamere Internment Camp","LordamereInternmentCamp",1},
{"Lothos Riftwaker","LothosRiftwaker",1},
{"Mage Quarter","MageQuarter",1},
{"Magic Quarter","MagicQuarter",1},
{"Maldens Orchard","MaldensOrchard",1},
{"Manor Mistmantle","ManorMistmantle",1},
{"Mardenholde Keep","MardenholdeKeep",1},
{"Mazra Alor","MazraAlor",1},
{"Menethil Bay","MenethilBay",1},
{"Mirage Flats","MirageFlats",1},
{"Mirror Lake","MirrorLake",1},
{"Mirror Lake Orchard","MirrorLakeOrchard",1},
{"Mistvale Valley","MistvaleValley",1},
{"Misty Pine Refuge","MistyPineRefuge",1},
{"Misty Reed Post","MistyReedPost",1},
{"Misty Reed Strand","MistyReedStrand",1},
{"Misty Shore","MistyShore",1},
{"Misty Valley","MistyValley",1},
{"Mizjah Ruins","MizjahRuins",1},
{"Mogrosh Stronghold","MogroshStronghold",1},
{"Moonbrook","Moonbrook",1},
{"Morgans Vigil","MorgansVigil",1},
{"Moshogg Ogre Mound","MoshoggOgreMound",1},
{"Mosshide Fen","MosshideFen",1},
{"Nek Mani Wellspring","NekManiWellspring",1},
{"Nesingwarys Expedition","NesingwarysExpedition",1},
{"Nethander Stead","NethanderStead",1},
{"Nethergarde Keep","NethergardeKeep",1},
{"Newmans Landing","NewmansLanding",1},
{"Nightmare Vale","NightmareVale",1},
{"Night Webs Hollow","NightWebsHollow",1},
{"Northdale","Northdale",1},
{"Northfold Manor","NorthfoldManor",1},
{"North Gate Outpost","NorthGateOutpost",1},
{"North Gate Pass","NorthGatePass",1},
{"Northpass Tower","NorthpassTower",1},
{"Northridge Lumber Camp","NorthridgeLumberCamp",1},
{"Northshire Valley","NorthshireValley",1},
{"Northshire Vineyards","NorthshireVineyards",1},
{"North Tides Hollow","NorthTidesHollow",1},
{"North Tides Run","NorthTidesRun",1},
{"Old Town","OldTown",1},
{"Olsens Farthing","OlsensFarthing",1},
{"Orb of Command","OrbOfCommand",1},
{"Ortells Hideout Dun Morogh","OrtellsHideoutDunMorogh",1},
{"Pestilent Scar ","PestilentScar ",1},
{"Plaguemist Ravine","PlaguemistRavine",1},
{"Plaguewood","Plaguewood",1},
{"Plaguewood Tower ","PlaguewoodTower ",1},
{"Pool of Tears","PoolOfTears",1},
{"Purgation Isle","PurgationIsle",1},
{"Pyrewood Village","PyrewoodVillage",1},
{"Quel Danil Lodge","QuelDanilLodge",2},
{"Quel Lithien Lodge","QuelLithienLodge",2},
{"Quel Thalas","QuelThalas",2},
{"Quel Thalas Tower","QuelThalasTower",2},
{"Raptor Ridge","RaptorRidge",1},
{"Raven Hill","RavenHill",1},
{"Raven Hill Cemetery","RavenHillCemetery",1},
{"Ravenholdt Manor","RavenholdtManor",1},
{"Rebel Camp","RebelCamp",1},
{"Redridge Canyons","RedridgeCanyons",1},
{"Redridge Mountains","RedridgeMountains",1},
{"Refuge Pointe","RefugePointe",1},
{"Renders Valley","RendersValley",1},
{"Rethban Caverns","RethbanCaverns",1},
{"Revantusk Village","RevantuskVillage",1},
{"Ridgepoint Tower","RidgepointTower",1},
{"Rise of the Defiler","RiseOfTheDefiler",1},
{"Rogues Quarter","RoguesQuarter",1},
{"Royal Quarter","RoyalQuarter",1},
{"Ruins of Aboraz","RuinsOfAboraz",1},
{"Ruins of Alterac","RuinsOfAlterac",1},
{"Ruins of Andorhal","RuinsOfAndorhal",1},
{"Ruins of Jubuwal","RuinsOfJubuwal",1},
{"Ruins of Lordaeron","RuinsOfLordaeron",1},
{"Ruins of Thaurissan","RuinsOfThaurissan",1},
{"Ruins of Zul Kunda","RuinsOfZulKunda",1},
{"Ruins of Zul Mamwe","RuinsOfZulMamwe",1},
{"Ruins of Zul Manwe","RuinsOfZulManwe",1},
{"Saldeans Farm","SaldeansFarm",1},
{"Saltspray Glen","SaltsprayGlen",1},
{"Scarlet Base Camp","ScarletBaseCamp",1},
{"Scarlet Monastery","ScarletMonastery",1},
{"Scarlet Watch Post","ScarletWatchPost",1},
{"Scholomance","Scholomance",1},
{"Searing Gorge","SearingGorge",1},
{"Sentinel Hill","SentinelHill",1},
{"Sentinel Tower","SentinelTower",1},
{"Seradane","Seradane",1},
{"Serpents Coil","SerpentsCoil",1},
{"Sewers","Sewers",1},
{"Shadow Fang Keep","ShadowFangKeep",1},
{"Shadow Grave","ShadowGrave",1},
{"Shadra Alor","ShadraAlor",1},
{"Shaol Watha","ShaolWatha",1},
{"Shimmer Ridge","ShimmerRidge",1},
{"Shindiggers Camp","ShindiggersCamp",1},
{"Shouthern Savage Coast","ShouthernSavageCoast",1},
{"Silverpine Forest","SilverpineForest",1},
{"Silverpine Forest Shadowfang Keep","SilverpineForestShadowfangKeep",1},
{"Silver Stream Mine","SilverStreamMine",1},
{"Skulk Rock","SkulkRock",1},
{"Slaughter Hollow","SlaughterHollow",1},
{"Sleeping Gorge","SleepingGorge",1},
{"Slither Rock","SlitherRock",1},
{"Solliden Farmstead","SollidenFarmstead",1},
{"Sorrow Hill","SorrowHill",1},
{"Sorrowmurk","Sorrowmurk",1},
{"Southern Savage Coast","SouthernSavageCoast",1},
{"South Gate Outpost","SouthGateOutpost",1},
{"South Gate Pass","SouthGatePass",1},
{"Southpoint Tower","SouthpointTower",1},
{"Southshore","Southshore",1},
{"Spirit Den","SpiritDen",1},
{"Splinterspear Junction","SplinterspearJunction",1},
{"Stagalbog Cave","StagalbogCave",1},
{"Steelgrills Depot","SteelgrillsDepot",1},
{"Stendels Pond","StendelsPond",1},
{"Stillwater Pond","StillwaterPond",1},
{"Stonard","Stonard",1},
{"Stone Cairn Lake","StoneCairnLake",1},
{"Stonesplinter Valley","StonesplinterValley",1},
{"Stonewatch","Stonewatch",1},
{"Stonewatch Falls","StonewatchFalls",1},
{"Stonewatch Keep","StonewatchKeep",1},
{"Stonewatch Tower","StonewatchTower",1},
{"Stonewrought Dam","StonewroughtDam",1},
{"Stormwind Harbor","StormwindHarbor",1},
{"Stormwind Keep","StormwindKeep",1},
{"Strahnbrad","Strahnbrad",1},
{"Stranglethorn Vale","StranglethornVale",1},
{"Stranglethorn Vale Unfinished Region","StranglethornValeUnfinishedRegion",1},
{"Stratholme","Stratholme",1},
{"Stromgarde Keep","StromgardeKeep",1},
{"Sundown Marsh","SundownMarsh",1},
{"Swamp of Sorrows","SwampOfSorrows",1},
{"Tanner Camp","TannerCamp",1},
{"Tarren Mill","TarrenMill",1},
{"Temple of Atal Hakkar","TempleOfAtalHakkar",1},
{"Terrace of Repose","TerraceOfRepose",1},
{"Terrordale","Terrordale",1},
{"Terrorweb Tunnel","TerrorwebTunnel",1},
{"Terror Wing Path","TerrorWingPath",1},
{"Thandol Span","ThandolSpan",1},
{"The Altar of Zul","TheAltarOfZul",1},
{"The Apothecarium","TheApothecarium",1},
{"The Bulwark","TheBulwark",1},
{"The Cape of Stranglethorn","TheCapeOfStranglethorn",1},
{"The Cauldron","TheCauldron",1},
{"The Corners","TheCorners",1},
{"The Creeping Ruin","TheCreepingRuin",1},
{"The Crystal Shore","TheCrystalShore",1},
{"The Dagger Hills","TheDaggerHills",1},
{"The Darkened Bank","TheDarkenedBank",1},
{"The Dark Portal","TheDarkPortal",1},
{"The Dawning Isles","TheDawningIsles",1},
{"The Dead Acre","TheDeadAcre",1},
{"The Dead Field","TheDeadField",1},
{"The Deadmines","TheDeadmines",1},
{"The Decrepit Ferry","TheDecrepitFerry",1},
{"The Drowned Reef","TheDrownedReef",1},
{"The Dustbowl","TheDustbowl",1},
{"The Dust Plains","TheDustPlains",1},
{"The Forbidding Sea Islands","TheForbiddingSeaIslands",1},
{"The Forlorn Cavern","TheForlornCavern",1},
{"The Fungal Vale","TheFungalVale",1},
{"The Grand Vestibule","TheGrandVestibule",1},
{"The Great Arena","TheGreatArena",1},
{"The Great Forge","TheGreatForge",1},
{"The Green Belt","TheGreenBelt",1},
{"The Greyname Wall","TheGreynameWall",1},
{"The Grinding Quarry","TheGrindingQuarry",1},
{"The Grizzled Den","TheGrizzledDen",1},
{"The Harborage","TheHarborage",1},
{"The Headland","TheHeadland",1},
{"The Hinterlands","TheHinterlands",1},
{"The Hushed Bank","TheHushedBank",1},
{"The Infectis Scar","TheInfectisScar",1},
{"The Ivar Patch","TheIvarPatch",1},
{"The Jansen Stead","TheJansenStead",1},
{"Thelgen Rock","ThelgenRock",1},
{"The Loch","TheLoch",1},
{"The Lost Fleet","TheLostFleet",1},
{"Thelsamar","Thelsamar",1},
{"The Maclure Vineyards","TheMaclureVineyards",1},
{"The Makers Terrace","TheMakersTerrace",1},
{"The Marris Stead","TheMarrisStead",1},
{"The Military Ward","TheMilitaryWard",1},
{"The Misty Ward","TheMistyWard",1},
{"The Molsen Farm","TheMolsenFarm",1},
{"The Molten Span","TheMoltenSpan",1},
{"The North Coast ","TheNorthCoast ",1},
{"The Noxious Glade ","TheNoxiousGlade ",1},
{"The Overlook Cliffs","TheOverlookCliffs",1},
{"The Park","ThePark",1},
{"The Pillar of Ash","ThePillarOfAsh",1},
{"The Rotting Orchard","TheRottingOrchard",1},
{"The Savage Coast","TheSavageCoast",1},
{"The Scarlet Basilica","TheScarletBasilica",1},
{"The Sea of Cinders","TheSeaOfCinders",1},
{"The Sepulcher","TheSepulcher",1},
{"The Shifting Mire","TheShiftingMire",1},
{"The Shining Strand","TheShiningStrand",1},
{"The Skittering Dark","TheSkitteringDark",1},
{"The Slag Pit","TheSlagPit",1},
{"The Stockade","TheStockade",1},
{"The Stockpile","TheStockpile",1},
{"T He Stonefield Farm","THeStonefieldFarm",1},
{"The Sunken Temple","TheSunkenTemple",1},
{"The Tainted Scar","TheTaintedScar",1},
{"The Temple of Atal Hakkar","TheTempleOfAtalHakkar",1},
{"The Temple of Tears","TheTempleOfTears",1},
{"The Tundrid Hills","TheTundridHills",1},
{"The Undercroft","TheUndercroft",1},
{"The Uplands","TheUplands",1},
{"The Vice","TheVice",1},
{"The Vile Reef","TheVileReef",1},
{"The Weeping Cave","TheWeepingCave",1},
{"The Writhing Haunt","TheWrithingHaunt",1},
{"The Yorgen Farmstead","TheYorgenFarmstead",1},
{"Thondroril River","ThondrorilRiver",1},
{"Thoradins Wall","ThoradinsWall",1},
{"Thorium Point","ThoriumPoint",1},
{"Thunder Falls","ThunderFalls",1},
{"Tinker Town","TinkerTown",1},
{"Tirisfal Glades","TirisfalGlades",1},
{"Tirisfal Glades Unfinished Region","TirisfalGladesUnfinishedRegion",1},
{"Tirisfal Glades Zeppelin","TirisfalGladesZeppelin",1},
{"Tkashi Ruins","TkashiRuins",1},
{"Top of Blackrock Mountain","TopOfBlackrockMountain",1},
{"Tower of Ilgalar","TowerOfIlgalar",1},
{"Tower of Llgalar","TowerOfLlgalar",1},
{"Trade District","TradeDistrict",1},
{"Trade Quarter","TradeQuarter",1},
{"Tranquil Gardens Cemetery","TranquilGardensCemetery",1},
{"Twilight Grove","TwilightGrove",1},
{"Tyrs Hand","TyrsHand",1},
{"Tyrs Hand Abbey","TyrsHandAbbey",1},
{"Uldaman","Uldaman",1},
{"Uthers Tomb","UthersTomb",1},
{"Valgans Field","ValgansField",1},
{"Valley of Fangs","ValleyOfFangs",1},
{"Valley of Kings","ValleyOfKings",1},
{"Valorwind Lake","ValorwindLake",1},
{"Venomweb Vale","VenomwebVale",1},
{"Venture Co Base Camp","VentureCoBaseCamp",1},
{"Vulgol Ogre Mound","VulgolOgreMound",1},
{"War Quarter","WarQuarter",1},
{"Westbrook Garrison","WestbrookGarrison",1},
{"Western Plaguelands","WesternPlaguelands",1},
{"Western Strand","WesternStrand",1},
{"Westfall","Westfall",1},
{"Westfall Lighthouse","WestfallLighthouse",1},
{"Wetlands","Wetlands",1},
{"Wetlands Dwarven Village","WetlandsDwarvenVillage",1},
{"Wetlands Hidden Spot","WetlandsHiddenSpot",1},
{"Whelgars Excavation Site","WhelgarsExcavationSite",1},
{"Whispering Gardens","WhisperingGardens",1},
{"Whispering Shore","WhisperingShore",1},
{"Wildhammer Keep","WildhammerKeep",1},
{"Wild Shore","WildShore",1},
{"Witherbark Village","WitherbarkVillage",1},
{"Wizards Sanctum","WizardsSanctum",1},
{"Yojamba Isle","YojambaIsle",1},
{"Ziatajai Ruins","ZiatajaiRuins",1},
{"Zul Gurub","ZulGurub",1},
{"Zul Gurub Stranglethorn Vale","ZulGurubStranglethornVale",1},
{"Zulmashar","Zulmashar",1},
{"Zun Watha","ZunWatha",1},
{"Zuuldaia Ruins","ZuuldaiaRuins",1},
} },
{ "Kalimdor", {
{"Abyssal Sands","AbyssalSands",1},
{"Agama Gor","AgamaGor",1},
{"Ahn Qiraj Backlands","AhnQirajBacklands",1},
{"Alcaz Island","AlcazIsland",1},
{"Aldrassil","Aldrassil",1},
{"Ameth Aran","AmethAran",1},
{"Ashenvale","Ashenvale",1},
{"Astranaar","Astranaar",1},
{"Auberdine","Auberdine",1},
{"Azshara","Azshara",1},
{"Bael Dun Digsite","BaelDunDigsite",1},
{"Bael Dun Keep","BaelDunKeep",1},
{"Bael Modan","BaelModan",1},
{"Ban Ethil Barrow Den","BanEthilBarrowDen",1},
{"Ban Ethil Hollow","BanEthilHollow",1},
{"Barrens","Barrens",1},
{"Bashal Aran","BashalAran",1},
{"Bathrans Haunt","BathransHaunt",1},
{"Bay of Storms","BayOfStorms",1},
{"Bears Head","BearsHead",1},
{"Beezils Wreck","BeezilsWreck",1},
{"Bitter Reaches","BitterReaches",1},
{"Blackfathom Deeps","BlackfathomDeeps",1},
{"Blackhoof Village","BlackhoofVillage",1},
{"Blackthorn Ridge","BlackthornRidge",1},
{"Blackwolf River","BlackwolfRiver",1},
{"Blackwood Den","BlackwoodDen",1},
{"Bladefist Bay","BladefistBay",1},
{"Bloodfen Burrow","BloodfenBurrow",1},
{"Bloodhoof Village","BloodhoofVillage",1},
{"Bloodtooth Camp","BloodtoothCamp",1},
{"Bloodvenom Falls","BloodvenomFalls",1},
{"Bloodvenom Post","BloodvenomPost",1},
{"Bloodvenom River","BloodvenomRiver",1},
{"Bluefen","Bluefen",1},
{"Bolgans Hole","BolgansHole",1},
{"Bough Shadow","BoughShadow",1},
{"Boulder Lode Mine","BoulderLodeMine",1},
{"Boulderslide Cavern","BoulderslideCavern",1},
{"Boulderslide Ravine","BoulderslideRavine",1},
{"Brackenwall Village","BrackenwallVillage",1},
{"Brambleblade Ravine","BramblebladeRavine",1},
{"Bramblescar","Bramblescar",1},
{"Broken Commons","BrokenCommons",1},
{"Broken Pillar","BrokenPillar",1},
{"Bronzebeard Encampment","BronzebeardEncampment",1},
{"Burning Blade Coven","BurningBladeCoven",1},
{"Camp Aparaje","CampAparaje",1},
{"Camp E Thok","CampEThok",1},
{"Camp Mojache","CampMojache",1},
{"Camp Narache","CampNarache",1},
{"Camp Taurajo","CampTaurajo",1},
{"Caverns of Time","CavernsOfTime",1},
{"Cenario Hold","CenarioHold",1},
{"Cenarion Enclave","CenarionEnclave",1},
{"Cenarion Hold","CenarionHold",1},
{"Cleft of Shadow","CleftOfShadow",1},
{"Cliffspring Falls","CliffspringFalls",1},
{"Cliffspring River","CliffspringRiver",1},
{"Craftmens Terrace","CraftmensTerrace",1},
{"Cragpool Lake","CragpoolLake",1},
{"Darkcloud Pinnacle","DarkcloudPinnacle",1},
{"Darkmist Cavern","DarkmistCavern",1},
{"Darkshore","Darkshore",1},
{"Darkspear Strand","DarkspearStrand",1},
{"Darkwhisper Gorge","DarkwhisperGorge",1},
{"Deadeye Shore","DeadeyeShore",1},
{"Deadwood Village","DeadwoodVillage",1},
{"Demon Fall Canyon","DemonFallCanyon",1},
{"Demon Fall Ridge","DemonFallRidge",1},
{"Desolace","Desolace",1},
{"Dire Maul East","DireMaulEast",1},
{"Dire Maul North","DireMaulNorth",1},
{"Dire Maul West","DireMaulWest",1},
{"Dolanaar","Dolanaar",1},
{"Dreadmist Den","DreadmistDen",1},
{"Dreadmist Peak","DreadmistPeak",1},
{"Dreadmurk Shore","DreadmurkShore",1},
{"Dream Bough","DreamBough",1},
{"Drygulch Ravine","DrygulchRavine",1},
{"Dunemaul Compound","DunemaulCompound",1},
{"Dun Mandarr","DunMandarr",1},
{"Durotar","Durotar",1},
{"Durotar Zeppelin","DurotarZeppelin",1},
{"Dustwallow Bay","DustwallowBay",1},
{"Dustwallow Marsh","DustwallowMarsh",1},
{"Dustwind Cave","DustwindCave",1},
{"Eastmoon Ruins","EastmoonRuins",1},
{"Echo Isles","EchoIsles",1},
{"Elder Rise","ElderRise",1},
{"Eldreth Row","EldrethRow",1},
{"Emberstrifes Den","EmberstrifesDen",1},
{"Emerald Sanctuary","EmeraldSanctuary",1},
{"Ethel Rethor","EthelRethor",1},
{"Falfarren River","FalfarrenRiver",1},
{"Fallen Sky Lake","FallenSkyLake",1},
{"Far Watch Post","FarWatchPost",1},
{"Fear Scar Vale","FearScarVale",1},
{"Feathermoon Stronghold","FeathermoonStronghold",1},
{"Felfire Hill","FelfireHill",1},
{"Felpaw Village","FelpawVillage",1},
{"Fel Rock","FelRock",1},
{"Felwood","Felwood",1},
{"Feralas","Feralas",1},
{"Field of Giants","FieldOfGiants",1},
{"Fire Plume Ridge","FirePlumeRidge",1},
{"Fire Scar Shrine","FireScarShrine",1},
{"Forest Song","ForestSong",1},
{"Forlorn Ridge","ForlornRidge",1},
{"Frayfeather Highlands","FrayfeatherHighlands",1},
{"Freewind Post","FreewindPost",1},
{"Frostfire Hot Springs","FrostfireHotSprings",1},
{"Frostsaber Rock","FrostsaberRock",1},
{"Frostwhisper Gorge","FrostwhisperGorge",1},
{"Fungal Rock","FungalRock",1},
{"Gate of Ahn Qiraj","GateOfAhnQiraj",1},
{"Gates of Ahn Qiraj","GatesOfAhnQiraj",1},
{"Gelkis Village","GelkisVillage",1},
{"Ghost Walker Post","GhostWalkerPost",1},
{"Gnarlpine Hold","GnarlpineHold",1},
{"Golakka Hot Springs","GolakkaHotSprings",1},
{"Gold Bug","GoldBug",1},
{"Gold Road","GoldRoad",1},
{"Gordunni Outpost","GordunniOutpost",1},
{"Greatwood Vale","GreatwoodVale",1},
{"Greenpaw Village","GreenpawVillage",1},
{"Grimtotem Compound","GrimtotemCompound",1},
{"Grimtotem Post","GrimtotemPost",1},
{"Groldom Farm","GroldomFarm",1},
{"Grommash Hold","GrommashHold",1},
{"Grove of the Ancients","GroveOfTheAncients",1},
{"Haldarr Encampment","HaldarrEncampment",1},
{"Hall of the Brave","HallOfTheBrave",1},
{"Hetaeras Clutch","HetaerasClutch",1},
{"Hidden Path","HiddenPath",1},
{"Highperch","Highperch",1},
{"High Wilderness","HighWilderness",1},
{"Hive Ashi","HiveAshi",1},
{"Hive Regal","HiveRegal",1},
{"Hive Zora","HiveZora",1},
{"Honors Stand","HonorsStand",1},
{"Hunter Rise","HunterRise",1},
{"Hyjal Summit","HyjalSummit",1},
{"Ice Thistle Hills","IceThistleHills",1},
{"Iris Lake","IrisLake",1},
{"Ironstone Camp","IronstoneCamp",1},
{"Ironstone Plateau","IronstonePlateau",1},
{"Irontree Cavern","IrontreeCavern",1},
{"Irontree Woods","IrontreeWoods",1},
{"Isle of Dread","IsleOfDread",1},
{"Jadefire Glen","JadefireGlen",1},
{"Jadefire Run","JadefireRun",1},
{"Jademir Lake","JademirLake",1},
{"Jaedenar","Jaedenar",1},
{"Jagged Reef","JaggedReef",1},
{"Jaggedswine Farm","JaggedswineFarm",1},
{"Kargathia Keep","KargathiaKeep",1},
{"Kodo Graveyard","KodoGraveyard",1},
{"Kodo Rock","KodoRock",1},
{"Kolgar Crag","KolgarCrag",1},
{"Kolgar Village","KolgarVillage",1},
{"Kormeks Hut","KormeksHut",1},
{"Lake Al Ameth","LakeAlAmeth",1},
{"Lake Elune Ara","LakeEluneAra",1},
{"Lake Falathim","LakeFalathim",1},
{"Lake Kel Theril","LakeKelTheril",1},
{"Lake Mennar","LakeMennar",1},
{"Lakkari Tar Pits","Lakkari TarPits",1},
{"Lakkari Tar Pits","LakkariTarPits",1},
{"Lands End Beach","LandsEndBeach",1},
{"Lariss Pavilion","LarissPavilion",1},
{"Legash Encampment","LegashEncampment",1},
{"Lost Point","LostPoint",1},
{"Lost Rigger Cove","LostRiggerCove",1},
{"Lower Wilds","LowerWilds",1},
{"Lushwater Oasis","LushwaterOasis",1},
{"Maestras Post","MaestrasPost",1},
{"Magram Village","MagramVillage",1},
{"Malaka Jin","MalakaJin",1},
{"Mannoroc Coven","MannorocCoven",1},
{"Maraudon","Maraudon",1},
{"Maraudon Orange","MaraudonOrange",1},
{"Maraudon Purple","MaraudonPurple",1},
{"Marshals Refuge","MarshalsRefuge",1},
{"Mazthoril","Mazthoril",1},
{"Mirage Raceway","MirageRaceway",1},
{"Mirkfallon Lake","MirkfallonLake",1},
{"Mists Edge","MistsEdge",1},
{"Moonglade","Moonglade",1},
{"Moonglade Horde Flypoint","MoongladeHordeFlypoint",1},
{"Morlos Aran","MorlosAran",1},
{"Morshan Base Camp","MorshanBaseCamp",1},
{"Mudsprocket","Mudsprocket",1},
{"Mulgore","Mulgore",1},
{"Mystral Lake","MystralLake",1},
{"Nats Landing","NatsLanding",1},
{"Nighthaven","Nighthaven",1},
{"Night Run","NightRun",1},
{"Nightsong Woods","NightsongWoods",1},
{"Nijels Point","NijelsPoint",1},
{"Noonshade Ruins","NoonshadeRuins",1},
{"North Point Tower","NorthPointTower",1},
{"Northwatch Hold","NorthwatchHold",1},
{"Old Hillsbrad Foothills","OldHillsbradFoothills",1},
{"Oneiros","Oneiros",1},
{"Onyxias Lair","OnyxiasLair",1},
{"Ortells Hideout","OrtellsHideout",1},
{"Owl Wing Thicket","OwlWingThicket",1},
{"Palemane Rock","PalemaneRock",1},
{"Pools of Arlithrien","PoolsOfArlithrien",1},
{"Prison","Prison",1},
{"Ragefire Chasm","RagefireChasm",1},
{"Rage Scar Hold","RageScarHold",1},
{"Ranazjar Isle","RanazjarIsle",1},
{"Raptor Grounds","RaptorGrounds",1},
{"Ravaged Caravan","RavagedCaravan",1},
{"Ravaged Twilight Camp","RavagedTwilightCamp",1},
{"Ravaged Twilight Capm","RavagedTwilightCapm",1},
{"Ravencrest Monument","RavencrestMonument",1},
{"Raynewood Retreat","RaynewoodRetreat",1},
{"Razorfen Downs","RazorfenDowns",1},
{"Razorfen Kraul","RazorfenKraul",1},
{"Razor Hill","RazorHill",1},
{"Razormane Grounds","RazormaneGrounds",1},
{"Razorwind Canyon","RazorwindCanyon",1},
{"Red Cloud Mesa","RedCloudMesa",1},
{"Red Rocks","RedRocks",1},
{"Remtravels Excavation","RemtravelsExcavation",1},
{"Roguefeather Den","RoguefeatherDen",1},
{"Ruins of Constellas","RuinsOfConstellas",1},
{"Ruins of Eldarath","RuinsOfEldarath",1},
{"Ruins of Isildien","RuinsOfIsildien",1},
{"Ruins of Mathystra","RuinsOfMathystra",1},
{"Ruins of Ravenwind","RuinsOfRavenwind",1},
{"Ruins of Solarsal","RuinsOfSolarsal",1},
{"Rut Theran Village","RutTheranVillage",1},
{"Sandsorrow Watch","SandsorrowWatch",1},
{"Sardor Isle","SardorIsle",1},
{"Sargeron","Sargeron",1},
{"Sar Theris Strand","SarTherisStrand",1},
{"Satyrnaar","Satyrnaar",1},
{"Scalebeards Cave","ScalebeardsCave",1},
{"Scrabblescrews Camp","ScrabblescrewsCamp",1},
{"Scuttle Coast","ScuttleCoast",1},
{"Senjin Village","SenjinVillage",1},
{"Sentry Point","SentryPoint",1},
{"Shadowbreak Ravine","ShadowbreakRavine",1},
{"Shadowglen","Shadowglen",1},
{"Shadow Hold","ShadowHold",1},
{"Shadowprey Village","ShadowpreyVillage",1},
{"Shadowsong Shrine","ShadowsongShrine",1},
{"Shadowthread Cave","ShadowthreadCave",1},
{"Shady Rest Inn","ShadyRestInn",1},
{"Shalzarus Lair","ShalzarusLair",1},
{"Shatter Scar Vale","ShatterScarVale",1},
{"Shatterspear Village","ShatterspearVillage",1},
{"Shrine of Remulos","ShrineOfRemulos",1},
{"Shrine of the Deceiver","ShrineOfTheDeceiver",1},
{"Shrine of the Dormant Flame","ShrineOfTheDormantFlame",1},
{"Silithus","Silithus",1},
{"Silithus Southern Farm","SilithusSouthernFarm",1},
{"Silithus Unfinished Region","SilithusUnfinishedRegion",1},
{"Silverwind Refuge","SilverwindRefuge",1},
{"Silverwing Grove","SilverwingGrove",1},
{"Silverwing Outpost","SilverwingOutpost",1},
{"Sishir Canyon","SishirCanyon",1},
{"Skull Rock","SkullRock",1},
{"Southbreak Shore","SouthbreakShore",1},
{"Southern Barrens","SouthernBarrens",1},
{"Southern Gold Road","SouthernGoldRoad",1},
{"Southfury River","SouthfuryRiver",1},
{"Southmoon Ruins","SouthmoonRuins",1},
{"Southridge Beach","SouthridgeBeach",1},
{"Southwind Village","SouthwindVillage",1},
{"Spirit Rise","SpiritRise",1},
{"Spirit Rock","SpiritRock",1},
{"Splintertree Post","SplintertreePost",1},
{"Splithoof Crag","SplithoofCrag",1},
{"Splithoof Hold","SplithoofHold",1},
{"Staghelm Point","StaghelmPoint",1},
{"Starbreeze Village","StarbreezeVillage",1},
{"Starfall Village","StarfallVillage",1},
{"Steamwheedle Port","SteamwheedlePort",1},
{"Stonebull Lake","StonebullLake",1},
{"Stonemaul Ruins","StonemaulRuins",1},
{"Stonetalon Mountains","StonetalonMountains",1},
{"Stonetalon Peak","StonetalonPeak",1},
{"Stormrage Barrow Dens","StormrageBarrowDens",1},
{"Sun Rock Retreat","SunRockRetreat",1},
{"Swamplight Manor","SwamplightManor",1},
{"Tahonda Ruins","TahondaRuins",1},
{"Talonbranch Glade","TalonbranchGlade",1},
{"Talrendis Point","TalrendisPoint",1},
{"Tanaris","Tanaris",1},
{"Teldrassil","Teldrassil",1},
{"Temple of Arkkoran","TempleOfArkkoran",1},
{"Temple of the Moon","TempleOfTheMoon",1},
{"Temple of Zin Malor","TempleOfZinMalor",1},
{"Terror Run","TerrorRun",1},
{"Tethris Aran","TethrisAran",1},
{"Thalanaar","Thalanaar",1},
{"Thalassian Base Camp","ThalassianBaseCamp",1},
{"The Barrens","TheBarrens",1},
{"The Black Morass","TheBlackMorass",1},
{"The Charred Valed","TheCharredValed",1},
{"The Cleft","TheCleft",1},
{"The Crossroads","TheCrossroads",1},
{"The Crystal Vale","TheCrystalVale",1},
{"The Culling of Stratholme","TheCullingOfStratholme",1},
{"The Den","TheDen",1},
{"The Den of Flame","TheDenOfFlame",1},
{"The Dor Danil Barrow Den","TheDorDanilBarrowDen",1},
{"The Drag","TheDrag",1},
{"The Dragonmurk","TheDragonmurk",1},
{"The Dry Hills","TheDryHills",1},
{"The Forgotten Coast","TheForgottenCoast",1},
{"The Forgotten Pools","TheForgottenPools",1},
{"The Gaping Chasm","TheGapingChasm",1},
{"The Golden Plains","TheGoldenPlains",1},
{"The Great Lift","TheGreatLift",1},
{"The Hidden Cove","TheHiddenCove",1},
{"The Howling Vale","TheHowlingVale",1},
{"The Long Wash","TheLongWash",1},
{"The Marshlands","TheMarshlands",1},
{"The Masters Glaive","TheMastersGlaive",1},
{"The Maul","TheMaul",1},
{"The Merchant Coast","TheMerchantCoast",1},
{"The Mor Shan Rampart","TheMorShanRampart",1},
{"The Noxious Lair","TheNoxiousLair",1},
{"The Oracle Glade","TheOracleGlade",1},
{"The Pools of Vision","ThePoolsOfVision",1},
{"The Quagmire","TheQuagmire",1},
{"Theramore","Theramore",1},
{"Theramore Isle","TheramoreIsle",1},
{"The Ring of Valor","TheRingOfValor",1},
{"The Rolling Plains","TheRollingPlains",1},
{"The Ruined Reaches","TheRuinedReaches",1},
{"The Ruins of Ahn Qiraj","TheRuinsOfAhnQiraj",1},
{"The Ruins of Kel Theril","TheRuinsOfKelTheril",1},
{"The Ruins of Ordil Aran","TheRuinsOfOrdilAran",1},
{"The Ruins of Stardust","TheRuinsOfStardust",1},
{"The Rustmaul Dig Site","TheRustmaulDigSite",1},
{"The Scarab Dais","TheScarabDais",1},
{"The Scarab Wall","TheScarabWall",1},
{"The Scarad Walp","TheScaradWalp",1},
{"The Screeching Canyon","TheScreechingCanyon",1},
{"The Shady Nook","TheShadyNook",1},
{"The Shattered Strand","TheShatteredStrand",1},
{"The Shimmering Flats","TheShimmeringFlats",1},
{"The Shrine of Aessina","TheShrineOfAessina",1},
{"The Slithering Scar","TheSlitheringScar",1},
{"The Sludge Fen","TheSludgeFen",1},
{"The Stagnant Oasis","TheStagnantOasis",1},
{"The Swarming Pillar","TheSwarmingPillar",1},
{"The Talondeep Path","TheTalondeepPath",1},
{"The Talon Den","TheTalonDen",1},
{"The Temple Gardens","TheTempleGardens",1},
{"The Temple of Ahn Qiraj","TheTempleOfAhnQiraj",1},
{"The Twin Colossals","TheTwinColossals",1},
{"The Venture Co Mine","TheVentureCoMine",1},
{"The Wailing Caverns","TheWailingCaverns",1},
{"The Weathered Nook","TheWeatheredNook",1},
{"The Writhing Deep","TheWrithingDeep",1},
{"The Zoram Strand","TheZoramStrand",1},
{"Thistleshrub Valley","ThistleshrubValley",1},
{"Thorn Hill","ThornHill",1},
{"Thousand Needles","ThousandNeedles",1},
{"Thunder Axe Fortress","ThunderAxeFortress",1},
{"Thunderhorn Water Well","ThunderhornWaterWell",1},
{"Thunder Ridge","ThunderRidge",1},
{"Tidefury Cove","TidefuryCove",1},
{"Timbermaw Hold","TimbermawHold",1},
{"Timbermaw Post","TimbermawPost",1},
{"Tiragarde Keep","TiragardeKeep",1},
{"Tor Kren Farm","TorKrenFarm",1},
{"Tower of Althalaxx","TowerOfAlthalaxx",1},
{"Tower of Eldara","TowerOfEldara",1},
{"Twilight Base Camp","TwilightBaseCamp",1},
{"Twilight Outpost","TwilightOutpost",1},
{"Twilight Post","TwilightPost",1},
{"Twilight Shore","TwilightShore",1},
{"Twilights Run","TwilightsRun",1},
{"Twilight Vale","TwilightVale",1},
{"Uldum","Uldum",1},
{"Un Goro Crater","UnGoroCrater",1},
{"Ursolan","Ursolan",1},
{"Valley of Honor","ValleyOfHonor",1},
{"Valley of Spears","ValleyOfSpears",1},
{"Valley of Spirits","ValleyOfSpirits",1},
{"Valley of Strength","ValleyOfStrength",1},
{"Valley of the Watchers","ValleyOfTheWatchers",1},
{"Valley of Trials","ValleyOfTrials",1},
{"Valley of Wisdom","ValleyOfWisdom",1},
{"Valormok","Valormok",1},
{"Valors Rest","ValorsRest",1},
{"Verdantis River","VerdantisRiver",1},
{"Wailing Caverns","WailingCaverns",1},
{"Warriors Terrace","WarriorsTerrace",1},
{"Warsong Labor Camp","WarsongLaborCamp",1},
{"Warsong Lumber Camp","WarsongLumberCamp",1},
{"Waterspring Field","WaterspringField",1},
{"Wavestrider Beach","WavestriderBeach",1},
{"Weazels Crater","WeazelsCrater",1},
{"Webwinder Path","WebwinderPath",1},
{"Wellspring Lake","WellspringLake",1},
{"Wellspring River","WellspringRiver",1},
{"Whitereach Post","WhitereachPost",1},
{"Wildbend River","WildbendRiver",1},
{"Wildmane Water Well","WildmaneWaterWell",1},
{"Windbreak Canyon","WindbreakCanyon",1},
{"Windfury Ridge","WindfuryRidge",1},
{"Windshear Crag","WindshearCrag",1},
{"Windshear Mine","WindshearMine",1},
{"Winterfall Village","WinterfallVillage",1},
{"Winterspring","Winterspring",1},
{"Witch Hill","WitchHill",1},
{"Woodpaw Hills","WoodpawHills",1},
{"Wyrmbog","Wyrmbog",1},
{"Xavian","Xavian",1},
{"Zalashjis Den","ZalashjisDen",1},
{"Zoramgar Outpost","ZoramgarOutpost",1},
{"Zul Farrak","ZulFarrak",1},
} },
{ "Outland", {
{"Abandoned Armory","AbandonedArmory",2},
{"Access Shaft Zeon","AccessShaftZeon",2},
{"Aeris Landing","AerisLanding",2},
{"Aldor Rise","AldorRise",2},
{"Allerian Post","AllerianPost",2},
{"Allerian Stronghold","AllerianStronghold",2},
{"Altar of Shatar","AltarOfShatar",2},
{"Amani Catacombs","AmaniCatacombs",2},
{"Amani Pass","AmaniPass",2},
{"Amberweb Pass","AmberwebPass",2},
{"Ammen Fields","AmmenFields",2},
{"Ammen Ford","AmmenFord",2},
{"Ammen Vale","AmmenVale",2},
{"Ancestral Grounds","AncestralGrounds",2},
{"An Daroth","AnDaroth",2},
{"Andilien Estate","AndilienEstate",2},
{"Ango Rosh Grounds","AngoRoshGrounds",2},
{"Ango Rosh Stronghold","AngoRoshStronghold",2},
{"An Owyn","AnOwyn",2},
{"An Telas","AnTelas",2},
{"Area52","Area52",2},
{"Arklonis Ridge","ArklonisRidge",2},
{"Arklon Ruins","ArklonRuins",2},
{"Ata Mal Terrace","AtaMalTerrace",2},
{"Auchenai Crypts","AuchenaiCrypts",2},
{"Auchenai Grounds","AuchenaiGrounds",2},
{"Auchindoun","Auchindoun",2},
{"Axxarien","Axxarien",2},
{"Azurebreeze Coast","AzurebreezeCoast",2},
{"Azuremyst Isle","AzuremystIsle",2},
{"Azure Watch","AzureWatch",2},
{"Bashir Landing","BashirLanding",2},
{"Beryl Coast","BerylCoast",2},
{"Blacksilt Shore","BlacksiltShore",2},
{"Black Temple","BlackTemple",2},
{"Blackwind Lake","BlackwindLake",2},
{"Blackwind Valley","BlackwindValley",2},
{"Blackwing Coven","BlackwingCoven",2},
{"Bladed Gulch","BladedGulch",2},
{"Blades Edge Mountains","BladesEdgeMountains",2},
{"Bladespire Grounds","BladespireGrounds",2},
{"Bladespire Hold","BladespireHold",2},
{"Blades Run","BladesRun",2},
{"Blade Tooth Canyon","BladeToothCanyon",2},
{"Bladewood","Bladewood",2},
{"Bladspire Outpost","BladspireOutpost",2},
{"Bleeding Hollow Ruins","BleedingHollowRuins",2},
{"Bleeding Ziggurat","BleedingZiggurat",2},
{"Bloodcurse Isle","BloodcurseIsle",2},
{"Bloodmaul Camp","BloodmaulCamp",2},
{"Bloodmaul Outpost","BloodmaulOutpost",2},
{"Bloodmaul Ravine","BloodmaulRavine",2},
{"Bloodmyst Isle","BloodmystIsle",2},
{"Bloodscale Enclave","BloodscaleEnclave",2},
{"Bloodscale Grounds","BloodscaleGrounds",2},
{"Blood Watch","BloodWatch",2},
{"Boha Mu Ruins","BohaMuRuins",2},
{"Bonechewer Ruins","BonechewerRuins",2},
{"Boulder Mok","BoulderMok",2},
{"Bristlelimb Enclave","BristlelimbEnclave",2},
{"Bristlelimb Village","BristlelimbVillage",2},
{"Broken Hill","BrokenHill",2},
{"Broken Wilds","BrokenWilds",2},
{"Burning Blade Ruins","BurningBladeRuins",2},
{"Camp of Boom","CampOfBoom",2},
{"Carrion Hill","CarrionHill",2},
{"Celestial Ridge","CelestialRidge",2},
{"Cenarion Post","CenarionPost",2},
{"Cenarion Refuge","CenarionRefuge",2},
{"Cenarion Thicket","CenarionThicket",2},
{"Chapel Yard","ChapelYard",2},
{"Circle of Blood Arena","CircleOfBloodArena",2},
{"Coilfang Reservoir","CoilfangReservoir",2},
{"Coilskar Cistern","CoilskarCistern",2},
{"Coilskar Point","CoilskarPoint",2},
{"Cosmowrench","Cosmowrench",2},
{"Court of the Sun","CourtOfTheSun",2},
{"Crash Site","CrashSite",2},
{"Crimson Watch","CrimsonWatch",2},
{"Crystal Spine","CrystalSpine",2},
{"Cursed Hollow","CursedHollow",2},
{"Daggerfen Village","DaggerfenVillage",2},
{"Daggermaw Canyon","DaggermawCanyon",2},
{"Darkcrest Enclave","DarkcrestEnclave",2},
{"Darkcrest Shore","DarkcrestShore",2},
{"Dawning Lane","DawningLane",2},
{"Dawnstar Spire","DawnstarSpire",2},
{"Deathforge Tower","DeathforgeTower",2},
{"Deatholme","Deatholme",2},
{"Deaths Door","DeathsDoor",2},
{"Den of Haal Esh","DenOfHaalEsh",2},
{"Derelict Caravan","DerelictCaravan",2},
{"Draenethystmine","Draenethystmine",2},
{"Dragonmaw Base Camp","DragonmawBaseCamp",2},
{"Dragonmaw Fortress","DragonmawFortress",2},
{"Dragons End","DragonsEnd",2},
{"Duskwither Grounds","DuskwitherGrounds",2},
{"Duskwither Spire","DuskwitherSpire",2},
{"Dustquill Ravine","DustquillRavine",2},
{"East Sanctum","EastSanctum",2},
{"Eclipse Point","EclipsePoint",2},
{"Eco Dome Farfield","EcoDomeFarfield",2},
{"Eco Dome Midrealm","EcoDomeMidrealm",2},
{"Eco Dome Sutheron","EcoDomeSutheron",2},
{"Elemental Plateau","ElementalPlateau",2},
{"Elrendar Falls","ElrendarFalls",2},
{"Elrendar River","ElrendarRiver",2},
{"Ethereum Staging Grounds","EthereumStagingGrounds",2},
{"Evergrove","Evergrove",2},
{"Eversong Woods","EversongWoods",2},
{"Expedition Armory","ExpeditionArmory",2},
{"Expedition Point","ExpeditionPoint",2},
{"Fairbreeze Village","FairbreezeVillage",2},
{"Fairbridge Strand","FairbridgeStrand",2},
{"Falcon Watch","FalconWatch",2},
{"Falconwing Square","FalconwingSquare",2},
{"Fallen Sky Ridge","FallenSkyRidge",2},
{"Falthrien Academy","FalthrienAcademy",2},
{"farstrider Enclave","farstriderEnclave",2},
{"Farstrider Retreat","FarstriderRetreat",2},
{"Farstriders Square","FarstridersSquare",2},
{"Feralfen Village","FeralfenVillage",2},
{"Feths Way","FethsWay",2},
{"Firewing Point","FirewingPoint",2},
{"Forge Base Gehenna","ForgeBaseGehenna",2},
{"Forge Base Oblivion","ForgeBaseOblivion",2},
{"Forge Camp Anger","ForgeCampAnger",2},
{"Forge Camp Fear","ForgeCampFear",2},
{"Forge Camp Hate","ForgeCampHate",2},
{"Forge Camp Mageddon","ForgeCampMageddon",2},
{"Forge Camp Rage","ForgeCampRage",2},
{"Forge Camp Terror","ForgeCampTerror",2},
{"Forge Camp Wrath","ForgeCampWrath",2},
{"Funggor Cavern","FunggorCavern",2},
{"Furywings Perch","FurywingsPerch",2},
{"Garadar","Garadar",2},
{"Geezles Camp","GeezlesCamp",2},
{"Ghostlands","Ghostlands",2},
{"Goldenbough Pass","GoldenboughPass",2},
{"Goldenmist Village","GoldenmistVillage",2},
{"Golden Strand","GoldenStrand",2},
{"Gor Gaz Outpost","GorGazOutpost",2},
{"Grangolvar Village","GrangolvarVillage",2},
{"Grishnath","Grishnath",2},
{"Gruuls Lair","GruulsLair",2},
{"Gyro Plank Bridge","GyroPlankBridge",2},
{"Haal Eshi Gorge","HaalEshiGorge",2},
{"Halaa","Halaa",2},
{"Halaani Basin","HalaaniBasin",2},
{"Hatchet Hills","HatchetHills",2},
{"Hellfire Citadel","HellfireCitadel",2},
{"Hellfire Peninsula","HellfirePeninsula",2},
{"Hellfire Ramparts","HellfireRamparts",2},
{"Hewn Bog","HewnBog",2},
{"Honor Hold","HonorHold",2},
{"Howling Ziggurat","HowlingZiggurat",2},
{"Huntress of the Sun","HuntressOfTheSun",2},
{"Illidari Point","IllidariPoint",2},
{"Insidions Perch","InsidionsPerch",2},
{"Invasion Point Annihilator","InvasionPointAnnihilator",2},
{"Invasion Point Cataclysm","InvasionPointCataclysm",2},
{"Invasion Point Overlord","InvasionPointOverlord",2},
{"Isle of Quel Danas","IsleOfQuelDanas",2},
{"Isle of Tribulations","IsleOfTribulations",2},
{"Jagged Ridge","JaggedRidge",2},
{"Kessels Crossing","KesselsCrossing",2},
{"Kilsorrow Fortress","KilsorrowFortress",2},
{"Kirin Var Village","KirinVarVillage",2},
{"Lake Elrendar","LakeElrendar",2},
{"Lake Ere Noru","LakeEreNoru",2},
{"Lake Jorune","LakeJorune",2},
{"Lake Sunspring","LakeSunspring",2},
{"Laughing Skull Ruins","LaughingSkullRuins",2},
{"Legion Hold","LegionHold",2},
{"Lower City","LowerCity",2},
{"Lower Veil Shil Ak","LowerVeilShilAk",2},
{"Mag Har Grounds","MagHarGrounds",2},
{"Mag Hari Procession","MagHariProcession",2},
{"Maghar Post","MagharPost",2},
{"Magisters Terrace","MagistersTerrace",2},
{"Magma Fields","MagmaFields",2},
{"Magtheridons Lair","MagtheridonsLair",2},
{"Manaforge Ara","ManaforgeAra",2},
{"Manaforge Bnaar","ManaforgeBnaar",2},
{"Manaforge Coruu","ManaforgeCoruu",2},
{"Manaforge Duro","ManaforgeDuro",2},
{"Manaforge Ultris","ManaforgeUltris",2},
{"Mana Tombs","ManaTombs",2},
{"Marshlight Lake","MarshlightLake",2},
{"Menagerie Wreckage","MenagerieWreckage",2},
{"Middenvale","Middenvale",2},
{"Midrealm Post","MidrealmPost",2},
{"Mok Nathal Village","MokNathalVillage",2},
{"Moongraze Woods","MoongrazeWoods",2},
{"Moonwing Den","MoonwingDen",2},
{"Muerder Row","MuerderRow",2},
{"Murder Eow","MurderEow",2},
{"Mystwood","Mystwood",2},
{"Nagrand","Nagrand",2},
{"Nazzivian","Nazzivian",2},
{"Nesingwary Safari","NesingwarySafari",2},
{"Nestlewood Hills","NestlewoodHills",2},
{"Nestlewood Thicket","NestlewoodThicket",2},
{"Netherstone","Netherstone",2},
{"Netherstorm","Netherstorm",2},
{"Netherweb Ridge","NetherwebRidge",2},
{"Netherwing Fields","NetherwingFields",2},
{"Netherwing Ledge","NetherwingLedge",2},
{"Netherwing Mines","NetherwingMines",2},
{"Netherwing Pass","NetherwingPass",2},
{"North Sanctum","NorthSanctum",2},
{"Northwind Cleft","NorthwindCleft",2},
{"Obsidias Perch","ObsidiasPerch",2},
{"Odesyu Landing","OdesyuLanding",2},
{"Ogrila","Ogrila",2},
{"Orebor Harborage","OreborHarborage",2},
{"Oronoks Farm","OronoksFarm",2},
{"Oshugun","Oshugun",2},
{"Pod Cluster","PodCluster",2},
{"Pod Wreckage","PodWreckage",2},
{"Pools of Aggonar","PoolsOfAggonar",2},
{"Portal Clearing","PortalClearing",2},
{"Protectorate Watch Post","ProtectorateWatchPost",2},
{"Quagg Ridge","QuaggRidge",2},
{"Ragefeather Ridge","RagefeatherRidge",2},
{"Ravens Wood","RavensWood",2},
{"Razaans Landing","RazaansLanding",2},
{"Razor Ridge","RazorRidge",2},
{"Razorthorn Rise","RazorthornRise",2},
{"Razorthorn Shelf","RazorthornShelf",2},
{"Razorthorn Trail","RazorthornTrail",2},
{"Reavers Fall","ReaversFall",2},
{"Refugee Caravan","RefugeeCaravan",2},
{"Ring of Observance","RingOfObservance",2},
{"Rivendarks Perch","RivendarksPerch",2},
{"Ruins of Baa Ri","RuinsOfBaaRi",2},
{"Ruins of Enkaat","RuinsOfEnkaat",2},
{"Ruins of Farahlon","RuinsOfFarahlon",2},
{"Ruins of Karabor","RuinsOfKarabor",2},
{"Ruins of Loreth Aran","RuinsOfLorethAran",2},
{"Ruins of Sha Naar","RuinsOfShaNaar",2},
{"Ruins of Silvermoon","RuinsOfSilvermoon",2},
{"Runestone Falithas","RunestoneFalithas",2},
{"Runestone Shandor","RunestoneShandor",2},
{"Ruuan Weald","RuuanWeald",2},
{"Saltherils Haven","SaltherilsHaven",2},
{"Sanctum of the Moon","SanctumOfTheMoon",2},
{"Sanctum of the Stars","SanctumOfTheStars",2},
{"Sanctum of the Sun","SanctumOfTheSun",2},
{"Scalewing Shelf","ScalewingShelf",2},
{"Scryers Tier","ScryersTier",2},
{"Seat of the Naaru","SeatOfTheNaaru",2},
{"Serpentshrine Cavern","SerpentshrineCavern",2},
{"Sethekk Halls","SethekkHalls",2},
{"Shadow Labyrinth","ShadowLabyrinth",2},
{"Shadowmoon Village","ShadowmoonVillage",2},
{"Shadow Tomb","ShadowTomb",2},
{"Shalandis Isle","ShalandisIsle",2},
{"Sha Naari Wastes","ShaNaariWastes",2},
{"Shartuuls Transporter","ShartuulsTransporter",2},
{"Sha Tari Base Camp","ShaTariBaseCamp",2},
{"Shattered Plains","ShatteredPlains",2},
{"Shattered Sun Staging","ShatteredSunStaging",2},
{"Shatter Point","ShatterPoint",2},
{"Shrine of Dathremar","ShrineOfDathremar",2},
{"Silting Shore","SiltingShore",2},
{"Silvermyst Isle","SilvermystIsle",2},
{"Singing Ridge","SingingRidge",2},
{"Skald","Skald",2},
{"Sketh Lon Base Camp","SkethLonBaseCamp",2},
{"Sketh Lon Wreckage","SkethLonWreckage",2},
{"Skethyl Mountains","SkethylMountains",2},
{"Skettis","Skettis",2},
{"Skulking Row","SkulkingRow",2},
{"Skyguard Outpost","SkyguardOutpost",2},
{"Slag Watch","SlagWatch",2},
{"Socrethars Seat","SocretharsSeat",2},
{"Sorrow Wing Point","SorrowWingPoint",2},
{"Soulgrinders Barrow","SoulgrindersBarrow",2},
{"Southern Rampart","SouthernRampart",2},
{"Southwind Cleft","SouthwindCleft",2},
{"Spinebreaker Post","SpinebreakerPost",2},
{"Spirit Fields","SpiritFields",2},
{"Sporeggar","Sporeggar",2},
{"Stillpine Hold","StillpineHold",2},
{"Stillwhisper Pond","StillwhisperPond",2},
{"Stonebreaker Hold","StonebreakerHold",2},
{"Stonewall Canyon","StonewallCanyon",2},
{"Suncrown Village","SuncrownVillage",2},
{"Sunctum of the Sun","SunctumOfTheSun",2},
{"Sunfury Hold","SunfuryHold",2},
{"Sunfury Spire","SunfurySpire",2},
{"Sungraze Peak","SungrazePeak",2},
{"Sunsail Anchorage","SunsailAnchorage",2},
{"Sunspring Post","SunspringPost",2},
{"Sunstrider Isle","SunstriderIsle",2},
{"Sunwell Plateau","SunwellPlateau",2},
{"Swamprat Post","SwampratPost",2},
{"Sylvanaar","Sylvanaar",2},
{"Talon Stand","TalonStand",2},
{"Telaar","Telaar",2},
{"Telaari Basin","TelaariBasin",2},
{"Telathions Camp","TelathionsCamp",2},
{"Telredor","Telredor",2},
{"Tempest Keep","TempestKeep",2},
{"Temple of Telhamat","TempleOfTelhamat",2},
{"Terokkar Forest","TerokkarForest",2},
{"Terokks Rest","TerokksRest",2},
{"Terrace of Light","TerraceOfLight",2},
{"Thalassian Pass","ThalassianPass",2},
{"The Altar of Damnation","TheAltarOfDamnation",2},
{"The Altar of Shadows","TheAltarOfShadows",2},
{"The Arcatraz","TheArcatraz",2},
{"The Barrier Hills","TheBarrierHills",2},
{"The Bazaar","TheBazaar",2},
{"The Bloodcursed Reff","TheBloodcursedReff",2},
{"The Blood Furnace","TheBloodFurnace",2},
{"The Bone Wastes","TheBoneWastes",2},
{"The Botanica","TheBotanica",2},
{"The Crimson Reach","TheCrimsonReach",2},
{"The Cryocore","TheCryocore",2},
{"The Crystal Hall","TheCrystalHall",2},
{"The Dark Portal Outland","TheDarkPortalOutland",2},
{"The Dead Mire","TheDeadMire",2},
{"The Dead Scar","TheDeadScar",2},
{"The Deathforge","TheDeathforge",2},
{"The Eye","TheEye",2},
{"The Fel Pits","TheFelPits",2},
{"The Fetid Pool","TheFetidPool",2},
{"The Great Fissure","TheGreatFissure",2},
{"The Hand of Gul Dan","TheHandOfGulDan",2},
{"The Heap","TheHeap",2},
{"The Lagoon","TheLagoon",2},
{"The Legion Front","TheLegionFront",2},
{"The Living Grove","TheLivingGrove",2},
{"The Living Wood","TheLivingWood",2},
{"The Low Path","TheLowPath",2},
{"The Mechanar","TheMechanar",2},
{"The Overlook","TheOverlook",2},
{"The Path of Conquest","ThePathOfConquest",2},
{"The Path of Glory","ThePathOfGlory",2},
{"The Proving Grounds","TheProvingGrounds",2},
{"The Ring of Blood","TheRingOfBlood",2},
{"The Ring of Trials","TheRingOfTrials",2},
{"The Royal Exhange","TheRoyalExhange",2},
{"The Sanctum","TheSanctum",2},
{"The Scorched Grove","TheScorchedGrove",2},
{"The Scrap Field","TheScrapField",2},
{"The Shadow Stair","TheShadowStair",2},
{"The Shattered Halls","TheShatteredHalls",2},
{"The Slave Pens","TheSlavePens",2},
{"The Spawning Glen","TheSpawningGlen",2},
{"The Stadium","TheStadium",2},
{"The Stair of Destiny","TheStairOfDestiny",2},
{"The Steamvault","TheSteamvault",2},
{"The Stormspire","TheStormspire",2},
{"The Sunspire","TheSunspire",2},
{"The Twilight Ridge","TheTwilightRidge",2},
{"The Underbog","TheUnderbog",2},
{"The Vault of Lights","TheVaultOfLights",2},
{"The Vector Coil","TheVectorCoil",2},
{"The Veiled Sea","TheVeiledSea",2},
{"The Violet Tower","TheVioletTower",2},
{"The Vortex Fields","TheVortexFields",2},
{"The Warp Fields","TheWarpFields",2},
{"The Warp Piston","TheWarpPiston",2},
{"Thornfang Hill","ThornfangHill",2},
{"Thrallmar","Thrallmar",2},
{"Thrallmar Mine","ThrallmarMine",2},
{"Throne of Kiljaeden","ThroneOfKiljaeden",2},
{"Throne of the Elements","ThroneOfTheElements",2},
{"Thunderlord Stronghold","ThunderlordStronghold",2},
{"Thurons Livery","ThuronsLivery",2},
{"Tomb of Lights","TombOfLights",2},
{"Tor Watha","TorWatha",2},
{"Toshleys Station","ToshleysStation",2},
{"Town Square","TownSquare",2},
{"Traders Tier","TradersTier",2},
{"Traitors Cove","TraitorsCove",2},
{"Tranquillien","Tranquillien",2},
{"Tranquil Shore","TranquilShore",2},
{"Trelleum Mine","TrelleumMine",2},
{"Trogmas Claim","TrogmasClaim",2},
{"Tulumans Landing","TulumansLanding",2},
{"Tuurem","Tuurem",2},
{"Twin Spire Ruins","TwinSpireRuins",2},
{"Umbrafen Lake","UmbrafenLake",2},
{"Umbrafen Village","UmbrafenVillage",2},
{"Underlight Mines","UnderlightMines",2},
{"Upper Veil Shil Ak","UpperVeilShilAk",2},
{"Valley of Bones","ValleyOfBones",2},
{"Veil Ala Rak","VeilAlaRak",2},
{"Veil Harr Ik","VeilHarrIk",2},
{"Veil Lashh","VeilLashh",2},
{"Veil Lithic","VeilLithic",2},
{"Veil Rhaze","VeilRhaze",2},
{"Veil Ruuan","VeilRuuan",2},
{"Veil Shalas","VeilShalas",2},
{"Veil Shienor","VeilShienor",2},
{"Veil Skith","VeilSkith",2},
{"Veil Vekh","VeilVekh",2},
{"Vekhaar Stand","VekhaarStand",2},
{"Veridian Point","VeridianPoint",2},
{"Vim Gols Circle","VimGolsCircle",2},
{"Vindicators Rest","VindicatorsRest",2},
{"Voidwind Plateau","VoidwindPlateau",2},
{"Vortex Pinnacle","VortexPinnacle",2},
{"Walk of Elders","WalkOfElders",2},
{"Wardens Cage","WardensCage",2},
{"Warmaul Hill","WarmaulHill",2},
{"West Sanctum","WestSanctum",2},
{"Wildhammer Stronghold","WildhammerStronghold",2},
{"Windrunner Spire","WindrunnerSpire",2},
{"Windrunner Village","WindrunnerVillage",2},
{"Wizard Row","WizardRow",2},
{"Worlds End Tavern","WorldsEndTavern",2},
{"Wrathscale Lair","WrathscaleLair",2},
{"Wrathscale Point","WrathscalePoint",2},
{"Writhing Mound","WrithingMound",2},
{"Wyrmscar Island","WyrmscarIsland",2},
{"Wyrmskull Bridge","WyrmskullBridge",2},
{"Wyrmskull Tunnel","WyrmskullTunnel",2},
{"Zabrajin","Zabrajin",2},
{"Zangarmarsh","Zangarmarsh",2},
{"Zangar Ridge","ZangarRidge",2},
{"Zeb Nowa","ZebNowa",2},
{"Zeb Sora","ZebSora",2},
{"Zeb Tela","ZebTela",2},
{"Zeb Watha","ZebWatha",2},
{"Zeppelin Crash","ZeppelinCrash",2},
{"Zeth Gor","ZethGor",2},
{"Zul Aman","ZulAman",2},
} },
{ "Northrend", {
{"7th Legion Front","7thLegionFront",4},
{"Abandoned Camp","AbandonedCamp",4},
{"Agmars Hammer","AgmarsHammer",4},
{"A Heros Welcome","AHerosWelcome",4},
{"Ahn Kahet","AhnKahet",4},
{"Aldurthar the Desolation Gate","AldurtharTheDesolationGate",4},
{"All That Glitters Prospecting Co","AllThatGlittersProspectingCo",4},
{"Altar of Harkoa","AltarOfHarkoa",4},
{"Altar of Mamtoth","AltarOfMamtoth",4},
{"Altar of Quetzlun","AltarOfQuetzlun",4},
{"Altar of Rhunok","AltarOfRhunok",4},
{"Altar of Sseratus","AltarOfSseratus",4},
{"Amber Ledge","AmberLedge",4},
{"Amberpine Lodge","AmberpineLodge",4},
{"Amphitheater of Anguish","AmphitheaterOfAnguish",4},
{"Angrathar the Wrathgate","AngratharTheWrathgate",4},
{"Antonidas Memorial","AntonidasMemorial",4},
{"Apothecary Camp","ApothecaryCamp",4},
{"Argent Tournament","ArgentTournament",4},
{"Ashwood Post","AshwoodPost",4},
{"Aspen Grove Post","AspenGrovePost",4},
{"Azjol Nerub","AzjolNerub",4},
{"Azure Dragonshrine","AzureDragonshrine",4},
{"Baelguns Excavation Site","BaelgunsExcavationSite",4},
{"Balargarde Fortress","BalargardeFortress",4},
{"Baleheim","Baleheim",4},
{"Balejar Watch","BalejarWatch",4},
{"Barbershop","Barbershop",4},
{"Beryl Point","BerylPoint",4},
{"Bittertide Lake","BittertideLake",4},
{"Blackriver Logging Camp","BlackriverLoggingCamp",4},
{"Bleeding Vale","BleedingVale",4},
{"Blistering Pool","BlisteringPool",4},
{"Bloodmoon Isle","BloodmoonIsle",4},
{"Bloodspore Plains","BloodsporePlains",4},
{"Blue Sky Logging Grounds","BlueSkyLoggingGrounds",4},
{"Borean Tundra","BoreanTundra",4},
{"Borgorok Outpost","BorgorokOutpost",4},
{"Bors Breath","BorsBreath",4},
{"Bronze Dragonshrine","BronzeDragonshrine",4},
{"Brunnhildar Village","BrunnhildarVillage",4},
{"Caldemere Lake","CaldemereLake",4},
{"Camp Oneqwah","CampOneqwah",4},
{"Camp Tunkalo","CampTunkalo",4},
{"Camp Winterhoof","CampWinterhoof",4},
{"Cantrips Crows","CantripsCrows",4},
{"Cartier Co Fine Jewelry","CartierCoFineJewelry",4},
{"Cathedral of Darkness","CathedralOfDarkness",4},
{"Cauldros Isle","CauldrosIsle",4},
{"Central Bridge","CentralBridge",4},
{"Chamber of Aspects","ChamberOfAspects",4},
{"Chillmere Coast","ChillmereCoast",4},
{"Circle of Wills","CircleOfWills",4},
{"Coast of Echoes","CoastOfEchoes",4},
{"Coldarra","Coldarra",4},
{"Coldrock Quarry","ColdrockQuarry",4},
{"Coldwind Heights","ColdwindHeights",4},
{"Coldwind Pass","ColdwindPass",4},
{"Conquest Hold","ConquestHold",4},
{"Corprethar the Horror Gate","CorpretharTheHorrorGate",4},
{"Crusaders Landing","CrusadersLanding",4},
{"Crystalsong Forest","CrystalsongForest",4},
{"Crystalweb Cavern","CrystalwebCavern",4},
{"Curiosities Moore","CuriositiesMoore",4},
{"Daggercap Bay","DaggercapBay",4},
{"Dalaran Merchants Bank","DalaranMerchantsBank",4},
{"Dalaran Sewer","DalaranSewer",4},
{"Dalaran Visitor Center","DalaranVisitorCenter",4},
{"Dargaths Demise","DargathsDemise",4},
{"Deaths Hand Encampment","DeathsHandEncampment",4},
{"Deaths Stand","DeathsStand",4},
{"DEHTA Encampment","DEHTAEncampment",4},
{"Dens of Dying","DensOfDying",4},
{"Derelict Strand","DerelictStrand",4},
{"Dragonblight","Dragonblight",4},
{"Dragons Fall","DragonsFall",4},
{"Dragonspine Tributary","DragonspineTributary",4},
{"Drak Agal","DrakAgal",4},
{"Drakatal Passage","DrakatalPassage",4},
{"Drakiljin Ruins","DrakiljinRuins",4},
{"Drak Mabwa","DrakMabwa",4},
{"Drak Sotra","DrakSotra",4},
{"Drak Sotra Fields","DrakSotraFields",4},
{"Drak Tharon Keep","DrakTharonKeep",4},
{"Dubra Jin","DubraJin",4},
{"Dun Argol","DunArgol",4},
{"Dun Niffelem","DunNiffelem",4},
{"Eastern Bridge","EasternBridge",4},
{"Eastspark Workshop","EastsparkWorkshop",4},
{"Ebon Watch","EbonWatch",4},
{"Eldritch Heights","EldritchHeights",4},
{"Ember Clutch","EmberClutch",4},
{"Ember Spear Tower","EmberSpearTower",4},
{"Emerald Dragonshrine","EmeraldDragonshrine",4},
{"Engine of the Makers","EngineOfTheMakers",4},
{"Evergreen Trading Post","EvergreenTradingPost",4},
{"Excavation Lift","ExcavationLift",4},
{"Explorers League Outpost","ExplorersLeagueOutpost",4},
{"Farshire","Farshire",4},
{"Farshire Lighthouse","FarshireLighthouse",4},
{"Farshire Mine","FarshireMine",4},
{"First Legion Foward Camp","FirstLegionFowardCamp",4},
{"Fizzcrank Airstrip","FizzcrankAirstrip",4},
{"Fizzcrank Pumping Station","FizzcrankPumpingStation",4},
{"Fjorns Anvil","FjornsAnvil",4},
{"Flamewatch Tower","FlamewatchTower",4},
{"Fordragon Hold","FordragonHold",4},
{"Forests Edge Post","ForestsEdgePost",4},
{"Forge of Fate","ForgeOfFate",4},
{"Forlorn Woods","ForlornWoods",4},
{"Fort Wildervar","FortWildervar",4},
{"Frenzyheart Hill","FrenzyheartHill",4},
{"Frenzyheart River","FrenzyheartRiver",4},
{"Frostblade Peak","FrostbladePeak",4},
{"Frostfield Lake","FrostfieldLake",4},
{"Frosthold","Frosthold",4},
{"Frostmourne Cavern","FrostmourneCavern",4},
{"Frozen Reach","FrozenReach",4},
{"Galakronds Rest","GalakrondsRest",4},
{"Garm","Garm",4},
{"Garms Bane","GarmsBane",4},
{"Garroshs Landing","GarroshsLanding",4},
{"Garvans Reef","GarvansReef",4},
{"Giants Run","GiantsRun",4},
{"Gjalerbron","Gjalerbron",4},
{"Glacial Falls","GlacialFalls",4},
{"Glimmer Bay","GlimmerBay",4},
{"Glorious Goods","GloriousGoods",4},
{"Granite Springs","GraniteSprings",4},
{"Grizzlemaw","Grizzlemaw",4},
{"Grizzly Hills","GrizzlyHills",4},
{"Gromarsh Crash Site","GromarshCrashSite",4},
{"Gundrak","Gundrak",4},
{"Gundrak Dungeon","GundrakDungeon",4},
{"Halgrind","Halgrind",4},
{"Hall of Horrors","HallOfHorrors",4},
{"Hall of the Shaper","HallOfTheShaper",4},
{"Halls of Lightning","HallsOfLightning",4},
{"Halls of Reflection","HallsOfReflection",4},
{"Halls of Stone","HallsOfStone",4},
{"Halls of the Ancestors","HallsOfTheAncestors",4},
{"Hearts Blood Shrine","HeartsBloodShrine",4},
{"Heartwood Trading Post","HeartwoodTradingPost",4},
{"Heb Drakkar","HebDrakkar",4},
{"Heb Valok","HebValok",4},
{"Hibernal Cavern","HibernalCavern",4},
{"Howling Fjord","HowlingFjord",4},
{"Hrothgars Landing","HrothgarsLanding",4},
{"Icecrown","Icecrown",4},
{"Icecrown Citadel Raid","IcecrownCitadelRaid",4},
{"Icecrown Glacier","IcecrownGlacier",4},
{"Icemist Village","IcemistVillage",4},
{"Indule Village","InduleVillage",4},
{"Ironwall Dam","IronwallDam",4},
{"Ironwall Rampart","IronwallRampart",4},
{"Ivalds Ruin","IvaldsRuin",4},
{"Jinthakalar","Jinthakalar",4},
{"Jotunheim","Jotunheim",4},
{"K3","K3",4},
{"Kamagua","Kamagua",4},
{"Kartaks Hold","KartaksHold",4},
{"Kaskala","Kaskala",4},
{"Kolramas","Kolramas",4},
{"Korkron Vanguard","KorkronVanguard",4},
{"Krasus Landing","KrasusLanding",4},
{"Kulgalar Keep","KulgalarKeep",4},
{"Lake Cauldros","LakeCauldros",4},
{"Lake Indule","LakeIndule",4},
{"Lake Kumuya","LakeKumuya",4},
{"Lakeside Landing","LakesideLanding",4},
{"Langroms Leather Links","LangromsLeatherLinks",4},
{"Legendary Leathers","LegendaryLeathers",4},
{"Lights Breach","LightsBreach",4},
{"Lights Trust","LightsTrust",4},
{"Like Clockwork","LikeClockwork",4},
{"Magical Menagerie","MagicalMenagerie",4},
{"Magmoth","Magmoth",4},
{"Magus Commerce Exchange","MagusCommerceExchange",4},
{"Makers Overlook","MakersOverlook",4},
{"Malykriss the Vile Hold","MalykrissTheVileHold",4},
{"Mamtoth Crater","MamtothCrater",4},
{"Maw of Neltharion","MawOfNeltharion",4},
{"Mid Point Station","MidPointStation",4},
{"Midwall Lift","MidwallLift",4},
{"Mightstone Quarry","MightstoneQuarry",4},
{"Moonrest Gardens","MoonrestGardens",4},
{"Mordrethar the Death Gate","MordretharTheDeathGate",4},
{"Mosswalker Village","MosswalkerVillage",4},
{"Narvirs Cradle","NarvirsCradle",4},
{"Naxxramas","Naxxramas",4},
{"Naxxramas Outside","NaxxramasOutside",4},
{"Nesingwary Base Camp","NesingwaryBaseCamp",4},
{"New Agamand","NewAgamand",4},
{"New Hearthglen","NewHearthglen",4},
{"Nidavelir","Nidavelir",4},
{"Nifflevar","Nifflevar",4},
{"Njords Breath Bay","NjordsBreathBay",4},
{"Njorndar Village","NjorndarVillage",4},
{"North Point Station","NorthPointStation",4},
{"North Spear Tower","NorthSpearTower",4},
{"Nozzlerust Post","NozzlerustPost",4},
{"Obsidian Dragonshrine","ObsidianDragonshrine",4},
{"One More Glass","OneMoreGlass",4},
{"Onslaught Base Camp","OnslaughtBaseCamp",4},
{"Onslaught Harbor","OnslaughtHarbor",4},
{"Palea","Palea",4},
{"Path of the Titans","PathOfTheTitans",4},
{"Pit of Saron","PitOfSaron",4},
{"Plain of Echoes","PlainOfEchoes",4},
{"Plains of Nasam","PlainsOfNasam",4},
{"Pools of Jin Alai","PoolsOfJinAlai",4},
{"Pools of Zha Jin","PoolsOfZhaJin",4},
{"Quel Delars Rest","QuelDelarsRest",4},
{"Rageclaw Den","RageclawDen",4},
{"Rageclaw Lake","RageclawLake",4},
{"Rage Fang Shrine","RageFangShrine",4},
{"Rainspeaker Canopy","RainspeakerCanopy",4},
{"Rainspeaker Rapids","RainspeakerRapids",4},
{"Redwood Trading Post","RedwoodTradingPost",4},
{"Reliquary of Agony","ReliquaryOfAgony",4},
{"Reliquary of Pain","ReliquaryOfPain",4},
{"Rickets Folly","RicketsFolly",4},
{"Riplash Ruins","RiplashRuins",4},
{"Riplash Strand","RiplashStrand",4},
{"Rivenwood","Rivenwood",4},
{"Rivers Heart","RiversHeart",4},
{"Rohemdal Pass","RohemdalPass",4},
{"Ruby Dragonshrine","RubyDragonshrine",4},
{"Ruins of Drak Zin","RuinsOfDrakZin",4},
{"Ruins of Eldranath","RuinsOfEldranath",4},
{"Ruins of Shandaral","RuinsOfShandaral",4},
{"Ruins of Tethys","RuinsOfTethys",4},
{"Runeweaver Square","RuneweaverSquare",4},
{"Sanctum of Reanimation","SanctumOfReanimation",4},
{"Sands of Nasam","SandsOfNasam",4},
{"Sapphire Hive","SapphireHive",4},
{"Saronite Mines","SaroniteMines",4},
{"Savage Ledge","SavageLedge",4},
{"Scalawag Point","ScalawagPoint",4},
{"Scalding Pools","ScaldingPools",4},
{"Scarlet Point","ScarletPoint",4},
{"Scarlet Tower","ScarletTower",4},
{"Scourgeholme","Scourgeholme",4},
{"Shadowfang Tower","ShadowfangTower",4},
{"Shadowsight Tower","ShadowsightTower",4},
{"Shattered Straits","ShatteredStraits",4},
{"Shield Hill","ShieldHill",4},
{"Sholazar Basin","SholazarBasin",4},
{"Sifreldar Village","SifreldarVillage",4},
{"Silent Vigil","SilentVigil",4},
{"Silverbrook","Silverbrook",4},
{"Sindragosas Fall","SindragosasFall",4},
{"Sisters Sorcerous","SistersSorcerous",4},
{"Skorn","Skorn",4},
{"Snowblind Hills","SnowblindHills",4},
{"Snowblind Terrace","SnowblindTerrace",4},
{"Snowdrift Plains","SnowdriftPlains",4},
{"Snowfall Glade","SnowfallGlade",4},
{"Solstice Village","SolsticeVillage",4},
{"Sorlofs Strand","SorlofsStrand",4},
{"South Point Station","SouthPointStation",4},
{"Sparksocket Minefield","SparksocketMinefield",4},
{"Sparktouched Haven","SparktouchedHaven",4},
{"Spearborn Encampment","SpearbornEncampment",4},
{"Spire of Blood","SpireOfBlood",4},
{"Spire of Decay","SpireOfDecay",4},
{"Spire of Pain","SpireOfPain",4},
{"Stars Rest","StarsRest",4},
{"Steam Springs","SteamSprings",4},
{"Steel Gate","SteelGate",4},
{"Steeljaws Caravan","SteeljawsCaravan",4},
{"Stonewall Lift","StonewallLift",4},
{"Storm Peaks","StormPeaks",4},
{"Sunreavers Command","SunreaversCommand",4},
{"Sunreavers Sanctuary","SunreaversSanctuary",4},
{"Swindlegrins Dig","SwindlegrinsDig",4},
{"Talismanic Textiles","TalismanicTextiles",4},
{"Talramas","Talramas",4},
{"Tanks For Everything","TanksForEverything",4},
{"Taunkale Village","TaunkaleVillage",4},
{"Temple Cityof Enkilah","TempleCityofEnkilah",4},
{"Temple of Invention","TempleOfInvention",4},
{"Temple of Life","TempleOfLife",4},
{"Temple of Order","TempleOfOrder",4},
{"Temple of Storms","TempleOfStorms",4},
{"Temple of Winter","TempleOfWinter",4},
{"Temple of Wisdom","TempleOfWisdom",4},
{"Terrace of the Makers","TerraceOfTheMakers",4},
{"The Abandoned Reach","TheAbandonedReach",4},
{"The Agronomical Apothecary","TheAgronomicalApothecary",4},
{"The Ancient Lift","TheAncientLift",4},
{"The Argent Stand","TheArgentStand",4},
{"The Argent Vanguard","TheArgentVanguard",4},
{"The Arsernal Absolute","TheArsernalAbsolute",4},
{"The Avalanche","TheAvalanche",4},
{"The Azure Front","TheAzureFront",4},
{"The Bank of Dalaran","TheBankOfDalaran",4},
{"The Beer Garden","TheBeerGarden",4},
{"The Black Market","TheBlackMarket",4},
{"The Blighted Pool","TheBlightedPool",4},
{"The Bombardment","TheBombardment",4},
{"The Bonefields","TheBonefields",4},
{"The Breach","TheBreach",4},
{"The Briny Pinnacle","TheBrinyPinnacle",4},
{"The Broken Bluffs","TheBrokenBluffs",4},
{"The Broken Front","TheBrokenFront",4},
{"The Broken Temple","TheBrokenTemple",4},
{"The Broodmothers Next","TheBroodmothersNext",4},
{"The Carrion Fields","TheCarrionFields",4},
{"The Cauldron of Flames","TheCauldronOfFlames",4},
{"The Chilled Quagmire","TheChilledQuagmire",4},
{"The Circle of Suffering","TheCircleOfSuffering",4},
{"The Conflagration","TheConflagration",4},
{"The Court of Bones","TheCourtOfBones",4},
{"The Court of Skulls","TheCourtOfSkulls",4},
{"The Crimson Cathedral","TheCrimsonCathedral",4},
{"The Crystal Vice","TheCrystalVice",4},
{"The Dead Fields","TheDeadFields",4},
{"The Decrepit Flow","TheDecrepitFlow",4},
{"The Dragon Wastes","TheDragonWastes",4},
{"The Eventide","TheEventide",4},
{"The Eye of Eternity","TheEyeOfEternity",4},
{"The Filthy Animal","TheFilthyAnimal",4},
{"The Fleshwerks","TheFleshwerks",4},
{"The Flood Plains","TheFloodPlains",4},
{"The Forest of Shadows","TheForestOfShadows",4},
{"The Forge of Souls","TheForgeOfSouls",4},
{"The Forgotten Overlook","TheForgottenOverlook",4},
{"The Forgotten Shore","TheForgottenShore",4},
{"The Forlom Mine","TheForlomMine",4},
{"The Frozen Glade","TheFrozenGlade",4},
{"The Frozen Halls","TheFrozenHalls",4},
{"The Frozen Mine","TheFrozenMine",4},
{"The Geyser Fields","TheGeyserFields",4},
{"The Glimmering Pillar","TheGlimmeringPillar",4},
{"The Great Tree","TheGreatTree",4},
{"The Howling Hollow","TheHowlingHollow",4},
{"The Hunters Reach","TheHuntersReach",4},
{"The Isle of Spears","TheIsleOfSpears",4},
{"The Ledgerdemain Lounge","TheLedgerdemainLounge",4},
{"The Lifeblood Pillar","TheLifebloodPillar",4},
{"The Lost Lands","TheLostLands",4},
{"The Lost Passage","TheLostPassage",4},
{"The Makers Perch","TheMakersPerch",4},
{"The Militant Mystic","TheMilitantMystic",4},
{"The Mirror of Dawn","TheMirrorOfDawn",4},
{"The Mirror of Twilight","TheMirrorOfTwilight",4},
{"The Mosslight Pillar","TheMosslightPillar",4},
{"The Nexus","TheNexus",4},
{"The Nexus Dungeon","TheNexusDungeon",4},
{"The Obsidian Sanctum","TheObsidianSanctum",4},
{"The Oculus","TheOculus",4},
{"The Pit of Fiends","ThePitOfFiends",4},
{"The Pit of the Fang","ThePitOfTheFang",4},
{"The Ruby Sanctum","TheRubySanctum",4},
{"The Savage Thicket","TheSavageThicket",4},
{"The Scribes Sacellum","TheScribesSacellum",4},
{"The Seabreach Flow","TheSeabreachFlow",4},
{"The Shadow Vault","TheShadowVault",4},
{"The Silver Enclave","TheSilverEnclave",4},
{"The Skyreach Pillar","TheSkyreachPillar",4},
{"The Steppe of Life","TheSteppeOfLife",4},
{"The Stormwrights Shelf","TheStormwrightsShelf",4},
{"The Sundered Shard","TheSunderedShard",4},
{"The Sunken Ring","TheSunkenRing",4},
{"The Suntouched Pillar","TheSuntouchedPillar",4},
{"The Threads of Fate","TheThreadsOfFate",4},
{"The Twilight Rivulet","TheTwilightRivulet",4},
{"The Twisted Glade","TheTwistedGlade",4},
{"The Unbound Thicket","TheUnboundThicket",4},
{"The Underbelly East","TheUnderbellyEast",4},
{"The Underbelly Exit","TheUnderbellyExit",4},
{"The Underbelly West","TheUnderbellyWest",4},
{"The Underhalls","TheUnderhalls",4},
{"The Valley of Fallen Heroes","TheValleyOfFallenHeroes",4},
{"The Valley of Lost Hope","TheValleyOfLostHope",4},
{"The Vibrant Glade","TheVibrantGlade",4},
{"The Violet Citadel","TheVioletCitadel",4},
{"The Violet Gate","TheVioletGate",4},
{"The Violet Hold","TheVioletHold",4},
{"The Wailing Ziggurat","TheWailingZiggurat",4},
{"The Westrift","TheWestrift",4},
{"The Wonderworks","TheWonderworks",4},
{"Thor Modan","ThorModan",4},
{"Thorsons Post","ThorsonsPost",4},
{"Thorvalds Camp","ThorvaldsCamp",4},
{"Thryms End","ThrymsEnd",4},
{"Thunderfall","Thunderfall",4},
{"Torps Farm","TorpsFarm",4},
{"Transborea","Transborea",4},
{"Transitus Shield","TransitusShield",4},
{"Trial of the Champion","TrialOfTheChampion",4},
{"Trial of the Crusader","TrialOfTheCrusader",4},
{"Twin Shores","TwinShores",4},
{"Ufrangs Hall","UfrangsHall",4},
{"Uldis","Uldis",4},
{"Ulduar","Ulduar",4},
{"Ulduar Raid","UlduarRaid",4},
{"Unupe","Unupe",4},
{"Ursocs Den","UrsocsDen",4},
{"Utgarde Keep","UtgardeKeep",4},
{"Utgarde Pinnacle","UtgardePinnacle",4},
{"Valgarde","Valgarde",4},
{"Valhalas","Valhalas",4},
{"Valiance Keep","ValianceKeep",4},
{"Valkyrion","Valkyrion",4},
{"Valley of Ancient Winters","ValleyOfAncientWinters",4},
{"Valley of Echoes","ValleyOfEchoes",4},
{"Vault of Archavon","VaultOfArchavon",4},
{"Vengeance Landing","VengeanceLanding",4},
{"Vengeance Lift","VengeanceLift",4},
{"Vengeance Pass","VengeancePass",4},
{"Venomspite","Venomspite",4},
{"Venture Bay","VentureBay",4},
{"Violet Stand","VioletStand",4},
{"Voldrune","Voldrune",4},
{"Voltarus","Voltarus",4},
{"Vordrassil Pass","VordrassilPass",4},
{"Vordrassils Heart","VordrassilsHeart",4},
{"Vordrassils Tears","VordrassilsTears",4},
{"Warsong Granary","WarsongGranary",4},
{"Warsong Hold","WarsongHold",4},
{"Warsong Jetty","WarsongJetty",4},
{"Warsong Slaughterhouse","WarsongSlaughterhouse",4},
{"Waygate","Waygate",4},
{"Western Bridge","WesternBridge",4},
{"Westfall Brigade Encampment","WestfallBrigadeEncampment",4},
{"Westguard Keep","WestguardKeep",4},
{"West Point Station","WestPointStation",4},
{"Westspark Workshop","WestsparkWorkshop",4},
{"Westwind Lift","WestwindLift",4},
{"Westwind Refugee Camp","WestwindRefugeeCamp",4},
{"Whisper Gulch","WhisperGulch",4},
{"White Pine Trading Post","WhitePineTradingPost",4},
{"Wildervar Mine","WildervarMine",4},
{"Wildgrowth Mangal","WildgrowthMangal",4},
{"Windrunners Overlook","WindrunnersOverlook",4},
{"Winterfin Caverns","WinterfinCaverns",4},
{"Winterfin Retreat","WinterfinRetreat",4},
{"Winterfin Village","WinterfinVillage",4},
{"Wintergarde Keep","WintergardeKeep",4},
{"Wintergarde Mausoleum","WintergardeMausoleum",4},
{"Wintergrasp","Wintergrasp",4},
{"Wintergrasp Fortress","WintergraspFortress",4},
{"Winters Breath Lake","WintersBreathLake",4},
{"Winters Edge Tower","WintersEdgeTower",4},
{"Winters Terrace","WintersTerrace",4},
{"Wyrmrest Temple","WyrmrestTemple",4},
{"Ymirheim","Ymirheim",4},
{"Zeb Halak","ZebHalak",4},
{"Zeramas","Zeramas",4},
{"Zim Abwa","ZimAbwa",4},
{"Zimbos Hideout","ZimbosHideout",4},
{"Zim Rhuk","ZimRhuk",4},
{"Zim Torga","ZimTorga",4},
{"Zol Heb","ZolHeb",4},
{"Zol Maz Stronghold","ZolMazStronghold",4},
{"Zul Drak","ZulDrak",4},
} },
}
